import type { DataRow, GeneratedData, GenerationReport, ProjectSchema } from '../types'

const safeName=(value:string)=>value.replace(/[^a-zA-Z0-9_\u4e00-\u9fa5-]/g,'_')
const download=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const rowsFor=(data:GeneratedData,tableId:string)=>data[tableId]||[]
const clean=(row:DataRow)=>Object.fromEntries(Object.entries(row).filter(([k])=>k!=='_mock_meta'))
const encoder=new TextEncoder()
export const GENERATOR_VERSION='2.7.0'
export const neutralizeSpreadsheetFormula = (value:string) => /^[=+\-@\t\r]/.test(value) ? `'${value}` : value
const csvCell=(v:unknown,delimiter=',')=>{const raw=v==null?'':typeof v==='object'?JSON.stringify(v):String(v);const s=neutralizeSpreadsheetFormula(raw);return s.includes(delimiter)||/["\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
export function toCSV(rows:DataRow[],delimiter=','){if(!rows.length)return '';const keys=[...new Set(rows.flatMap(r=>Object.keys(clean(r))))];return [keys.join(delimiter),...rows.map(r=>keys.map(k=>csvCell(r[k],delimiter)).join(delimiter))].join('\n')}
export function exportRows(rows:DataRow[],format:'json'|'csv'|'postman',name='pairwise-cases') { const base=safeName(name);if(format==='csv')download(new Blob([toCSV(rows)],{type:'text/csv;charset=utf-8'}),`${base}.csv`);else download(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}),`${base}_${format==='postman'?'postman_':''}data.json`) }
const sqlValue=(v:unknown,dialect:string)=>{if(v==null)return'NULL';if(typeof v==='number')return String(v);if(typeof v==='boolean')return dialect==='postgres'?String(v):v?'1':'0';return `'${String(v).replaceAll("'","''")}'`}
export function toSQL(project:ProjectSchema,data:GeneratedData,dialect:'mysql'|'postgres'|'sqlite') {
  const quote=dialect==='mysql'?'`':'"'; const identifier=(value:string)=>`${quote}${value.replaceAll(quote,quote+quote)}${quote}`; const lines=[dialect==='mysql'?'SET FOREIGN_KEY_CHECKS=0;':'BEGIN;']
  for(const table of project.tables){const rows=rowsFor(data,table.id).map(clean);if(!rows.length)continue;const keys=Object.keys(rows[0]);lines.push(`DELETE FROM ${identifier(table.name)};`);for(let i=0;i<rows.length;i+=100){const batch=rows.slice(i,i+100);lines.push(`INSERT INTO ${identifier(table.name)} (${keys.map(identifier).join(', ')}) VALUES\n${batch.map(r=>`(${keys.map(k=>sqlValue(r[k],dialect)).join(', ')})`).join(',\n')};`)}}
  lines.push(dialect==='mysql'?'SET FOREIGN_KEY_CHECKS=1;':'COMMIT;');return lines.join('\n\n')
}

const yamlScalar=(value:unknown)=>{if(value===null)return'null';if(typeof value==='number'||typeof value==='boolean')return String(value);return JSON.stringify(String(value))}
export function toYAML(value:unknown,depth=0):string {const indent='  '.repeat(depth);if(Array.isArray(value))return value.map(item=>item&&typeof item==='object'?`${indent}-\n${toYAML(item,depth+1)}`:`${indent}- ${yamlScalar(item)}`).join('\n');if(value&&typeof value==='object')return Object.entries(value as Record<string,unknown>).map(([key,item])=>item&&typeof item==='object'?`${indent}${JSON.stringify(key)}:\n${toYAML(item,depth+1)}`:`${indent}${JSON.stringify(key)}: ${yamlScalar(item)}`).join('\n');return`${indent}${yamlScalar(value)}`}
const xmlEscape=(value:unknown)=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;')
export function toXML(project:ProjectSchema,data:GeneratedData){return`<?xml version="1.0" encoding="UTF-8"?>\n<mockData project="${xmlEscape(project.name)}" schemaVersion="${xmlEscape(project.version)}">\n${project.tables.map(table=>`  <table name="${xmlEscape(table.name)}">\n${rowsFor(data,table.id).map(row=>`    <row>\n${Object.entries(clean(row)).map(([key,value])=>`      <field name="${xmlEscape(key)}">${xmlEscape(typeof value==='object'?JSON.stringify(value):value)}</field>`).join('\n')}\n    </row>`).join('\n')}\n  </table>`).join('\n')}\n</mockData>\n`}
const reportMarkdown=(project:ProjectSchema,report:GenerationReport)=>`# ${project.name} 数据覆盖报告\n\n- Schema 版本：${project.version}\n- 随机种子：${project.seed}\n- 总数据量：${report.totalRows}\n- 正常数据：${report.normalRows}\n- 异常数据：${report.abnormalRows}\n- 生成耗时：${report.duration} ms\n\n## 覆盖情况\n\n${report.coverage.map(item=>`- ${item.label}：${item.value}%（${item.detail}）`).join('\n')}\n\n## 未覆盖项\n\n${report.gaps.length?report.gaps.map(item=>`- ${item.label}：${item.detail}`).join('\n'):'- 无，可以直接用于测试。'}\n\n## 质量检查\n\n${report.checks.map(item=>`- [${item.status==='pass'?'x':' '}] ${item.label}：${item.detail}`).join('\n')}\n`

type ExportFile={name:string;content:string|Uint8Array}
const asBytes=(content:ExportFile['content'])=>typeof content==='string'?encoder.encode(content):content
const crcTable=Array.from({length:256},(_,number)=>{let value=number;for(let bit=0;bit<8;bit++)value=(value&1)?0xedb88320^(value>>>1):value>>>1;return value>>>0})
const crc32=(bytes:Uint8Array)=>{let value=0xffffffff;for(const byte of bytes)value=crcTable[(value^byte)&255]^(value>>>8);return(value^0xffffffff)>>>0}
const zipDate=(date:Date)=>({time:(date.getHours()<<11)|(date.getMinutes()<<5)|(date.getSeconds()>>1),day:((date.getFullYear()-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate()})
const header=(size:number,fill:(view:DataView)=>void)=>{const bytes=new Uint8Array(size);fill(new DataView(bytes.buffer));return bytes}
const joinBytes=(parts:Uint8Array[])=>{const result=new Uint8Array(parts.reduce((sum,part)=>sum+part.length,0));let offset=0;for(const part of parts){result.set(part,offset);offset+=part.length}return result}

export function createZip(files:ExportFile[],createdAt=new Date()):Uint8Array {
  const local:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;const stamp=zipDate(createdAt)
  for(const file of files){const name=encoder.encode(file.name),content=asBytes(file.content),crc=crc32(content),localHeader=header(30,view=>{view.setUint32(0,0x04034b50,true);view.setUint16(4,20,true);view.setUint16(6,0x0800,true);view.setUint16(8,0,true);view.setUint16(10,stamp.time,true);view.setUint16(12,stamp.day,true);view.setUint32(14,crc,true);view.setUint32(18,content.length,true);view.setUint32(22,content.length,true);view.setUint16(26,name.length,true)});local.push(localHeader,name,content);const centralHeader=header(46,view=>{view.setUint32(0,0x02014b50,true);view.setUint16(4,20,true);view.setUint16(6,20,true);view.setUint16(8,0x0800,true);view.setUint16(10,0,true);view.setUint16(12,stamp.time,true);view.setUint16(14,stamp.day,true);view.setUint32(16,crc,true);view.setUint32(20,content.length,true);view.setUint32(24,content.length,true);view.setUint16(28,name.length,true);view.setUint32(42,offset,true)});central.push(centralHeader,name);offset+=localHeader.length+name.length+content.length}
  const centralSize=central.reduce((sum,part)=>sum+part.length,0),end=header(22,view=>{view.setUint32(0,0x06054b50,true);view.setUint16(8,files.length,true);view.setUint16(10,files.length,true);view.setUint32(12,centralSize,true);view.setUint32(16,offset,true)});return joinBytes([...local,...central,end])
}

const SHA256_K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]
const rotateRight=(value:number,bits:number)=>(value>>>bits)|(value<<(32-bits))
export function sha256Fallback(input:Uint8Array){const length=input.length,paddedLength=Math.ceil((length+9)/64)*64,bytes=new Uint8Array(paddedLength);bytes.set(input);bytes[length]=0x80;const view=new DataView(bytes.buffer);view.setUint32(paddedLength-4,length*8);let hash=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]
  for(let offset=0;offset<paddedLength;offset+=64){const words=new Uint32Array(64);for(let index=0;index<16;index++)words[index]=view.getUint32(offset+index*4);for(let index=16;index<64;index++){const a=words[index-15],b=words[index-2],s0=rotateRight(a,7)^rotateRight(a,18)^(a>>>3),s1=rotateRight(b,17)^rotateRight(b,19)^(b>>>10);words[index]=(words[index-16]+s0+words[index-7]+s1)>>>0}let[a,b,c,d,e,f,g,h]=hash;for(let index=0;index<64;index++){const s1=rotateRight(e,6)^rotateRight(e,11)^rotateRight(e,25),choice=(e&f)^(~e&g),temp1=(h+s1+choice+SHA256_K[index]+words[index])>>>0,s0=rotateRight(a,2)^rotateRight(a,13)^rotateRight(a,22),majority=(a&b)^(a&c)^(b&c),temp2=(s0+majority)>>>0;h=g;g=f;f=e;e=(d+temp1)>>>0;d=c;c=b;b=a;a=(temp1+temp2)>>>0}hash=hash.map((value,index)=>(value+[a,b,c,d,e,f,g,h][index])>>>0)}return hash.map(value=>value.toString(16).padStart(8,'0')).join('')}
const sha256=async(content:ExportFile['content'])=>{const bytes=asBytes(content);if(globalThis.crypto?.subtle)return[...new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256',bytes))].map(byte=>byte.toString(16).padStart(2,'0')).join('');return sha256Fallback(bytes)}
async function xlsxFile(project:ProjectSchema,data:GeneratedData):Promise<Uint8Array>{const XLSX=await import('xlsx');const wb=XLSX.utils.book_new();project.tables.forEach(table=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rowsFor(data,table.id).map(row=>Object.fromEntries(Object.entries(clean(row)).map(([key,value])=>[key,typeof value==='string'?neutralizeSpreadsheetFormula(value):value])))),table.name.slice(0,31)));return new Uint8Array(XLSX.write(wb,{type:'array',bookType:'xlsx'}))}

async function formatFiles(format:string,project:ProjectSchema,data:GeneratedData,report:GenerationReport,activeTableId:string):Promise<ExportFile[]>{const base=safeName(project.name),rows=rowsFor(data,activeTableId),cleanRows=rows.map(clean),json=JSON.stringify(cleanRows,null,2)
  if(format==='json')return[{name:`${base}.json`,content:JSON.stringify(data,null,2)}];if(format==='jsonl')return[{name:`${base}.jsonl`,content:rows.map(row=>JSON.stringify(row)).join('\n')}];if(format==='csv'||format==='tsv')return[{name:`${base}.${format}`,content:toCSV(rows,format==='tsv'?'\t':',')}];if(format==='yaml')return[{name:`${base}.yaml`,content:toYAML(data)+'\n'}];if(format==='xml')return[{name:`${base}.xml`,content:toXML(project,data)}];if(['mysql','postgres','sqlite'].includes(format))return[{name:`${base}_${format}.sql`,content:toSQL(project,data,format as 'mysql'|'postgres'|'sqlite')}];if(format==='xlsx')return[{name:`${base}.xlsx`,content:await xlsxFile(project,data)}];if(format==='postman')return[{name:`${base}_postman.json`,content:JSON.stringify(cleanRows,null,2)}];if(format==='playwright')return[{name:`${base}.playwright.ts`,content:`export const testCases = ${json} as const;\n`}];if(format==='cypress')return[{name:`${base}.cypress.ts`,content:`export const testCases = ${json} as const;\n`}];if(format==='jest')return[{name:`${base}.jest.ts`,content:`export const testCases = ${json} as const;\n`}];if(format==='pytest')return[{name:`test_${base}.py`,content:`import json\nimport pytest\n\nCASES = json.loads(${JSON.stringify(JSON.stringify(cleanRows))})\n\n@pytest.mark.parametrize("case", CASES)\ndef test_mock_case(case):\n    assert case is not None\n`}];if(format==='junit')return[{name:`${base}_junit.csv`,content:toCSV(rows)}];if(format==='markdown')return[{name:`${base}_report.md`,content:reportMarkdown(project,report)}];if(format==='bundle')return[{name:'data/all-tables.json',content:JSON.stringify(data,null,2)},...project.tables.map(table=>({name:`data/${safeName(table.name)}.csv`,content:toCSV(rowsFor(data,table.id))})),{name:'sql/mysql.sql',content:toSQL(project,data,'mysql')},{name:'sql/postgres.sql',content:toSQL(project,data,'postgres')},{name:'sql/sqlite.sql',content:toSQL(project,data,'sqlite')},{name:'reports/coverage.md',content:reportMarkdown(project,report)}];throw new Error(`不支持的导出格式：${format}`)}

export async function createExportPackage(format:string,project:ProjectSchema,data:GeneratedData,report:GenerationReport,activeTableId:string){const createdAt=new Date(),files=await formatFiles(format,project,data,report,activeTableId),manifestFiles=await Promise.all(files.map(async file=>({name:file.name,bytes:asBytes(file.content).length,sha256:await sha256(file.content)}))),manifest={manifestVersion:1,projectName:project.name,schemaVersion:project.version,randomSeed:project.seed,generatorVersion:GENERATOR_VERSION,format,generatedAt:report.generatedAt,packagedAt:createdAt.toISOString(),rows:report.totalRows,normalRows:report.normalRows,abnormalRows:report.abnormalRows,abnormalRatio:report.totalRows?Number((report.abnormalRows/report.totalRows).toFixed(6)):0,files:manifestFiles},manifestFile={name:'manifest.json',content:JSON.stringify(manifest,null,2)},zip=createZip([...files,manifestFile],createdAt);return{blob:new Blob([zip],{type:'application/zip'}),filename:`${safeName(project.name)}_${format}.zip`,manifest}}
export async function exportData(format:string,project:ProjectSchema,data:GeneratedData,report:GenerationReport,activeTableId:string){const packageResult=await createExportPackage(format,project,data,report,activeTableId);download(packageResult.blob,packageResult.filename)}
