export interface PairwiseConfig { name:string; values:string[] }
export type PairwiseRule = Record<string,string>

export function parsePairwiseRules(text:string,dimensions:PairwiseConfig[]):PairwiseRule[] {
  if(text.length>20_000)throw new Error('组合规则文本不能超过 20,000 个字符')
  const byName=new Map(dimensions.map(dimension=>[dimension.name,dimension.values])),lines=text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);if(lines.length>100)throw new Error('组合规则最多 100 行')
  return lines.map((line,index)=>{const rule:PairwiseRule={};for(const token of line.split(/[,，]/).map(item=>item.trim()).filter(Boolean)){const separator=token.indexOf('=');if(separator<1)throw new Error(`第 ${index+1} 行格式错误，请使用“维度=值”`);const name=token.slice(0,separator).trim(),value=token.slice(separator+1).trim(),values=byName.get(name);if(!values)throw new Error(`第 ${index+1} 行包含未知维度：${name}`);if(!values.includes(value))throw new Error(`第 ${index+1} 行的 ${name} 不包含候选值：${value}`);rule[name]=value}if(!Object.keys(rule).length)throw new Error(`第 ${index+1} 行没有有效条件`);return rule})
}

const pairKey=(a:number,av:string,b:number,bv:string)=>JSON.stringify([a,av,b,bv])
const isExcluded=(row:PairwiseRule,exclusions:PairwiseRule[])=>exclusions.some(rule=>Object.keys(rule).length>0&&Object.entries(rule).every(([key,value])=>row[key]===value))
const rowPairs=(dimensions:PairwiseConfig[],row:PairwiseRule)=>{const pairs:string[]=[];for(let i=0;i<dimensions.length;i++)for(let j=i+1;j<dimensions.length;j++)pairs.push(pairKey(i,row[dimensions[i].name],j,row[dimensions[j].name]));return pairs}
const completeCombination=(partial:PairwiseRule,dimensions:PairwiseConfig[],exclusions:PairwiseRule[],uncovered?:Set<string>):PairwiseRule|null=>{if(isExcluded(partial,exclusions))return null;const next=dimensions.findIndex(dimension=>partial[dimension.name]===undefined);if(next<0)return partial;const dimension=dimensions[next],assigned=dimensions.map((candidate,index)=>({candidate,index})).filter(({candidate})=>partial[candidate.name]!==undefined),values=[...dimension.values].sort((a,b)=>{const score=(value:string)=>assigned.reduce((sum,{candidate,index})=>{const left=Math.min(index,next),right=Math.max(index,next),leftValue=index<next?partial[candidate.name]:value,rightValue=index<next?value:partial[candidate.name];return sum+(uncovered?.has(pairKey(left,leftValue,right,rightValue))?1:0)},0);return score(b)-score(a)});for(const value of values){const completed=completeCombination({...partial,[dimension.name]:value},dimensions,exclusions,uncovered);if(completed)return completed}return null}
const possiblePairs=(dimensions:PairwiseConfig[],exclusions:PairwiseRule[])=>{const pairs=new Set<string>();for(let i=0;i<dimensions.length;i++)for(let j=i+1;j<dimensions.length;j++)for(const a of dimensions[i].values)for(const b of dimensions[j].values){const partial={[dimensions[i].name]:a,[dimensions[j].name]:b};if(completeCombination(partial,dimensions,exclusions))pairs.add(pairKey(i,a,j,b))}return pairs}

export function analyzePairwiseCoverage(dimensions:PairwiseConfig[],rows:PairwiseRule[],exclusions:PairwiseRule[]=[]){const required=possiblePairs(dimensions,exclusions),covered=new Set(rows.flatMap(row=>rowPairs(dimensions,row)).filter(pair=>required.has(pair))),missing=[...required].filter(pair=>!covered.has(pair)).map(pair=>{const[i,a,j,b]=JSON.parse(pair) as[number,string,number,string];return`${dimensions[i].name}=${a} × ${dimensions[j].name}=${b}`});return{total:required.size,covered:covered.size,missing,percentage:required.size?Math.round(covered.size/required.size*100):100}}

export function generatePairwise(dimensions:PairwiseConfig[],options:{exclusions?:PairwiseRule[];forced?:PairwiseRule[]}={}){if(!dimensions.length)return[];if(dimensions.length<2||dimensions.length>8)throw new Error('Pairwise 需要 2–8 个维度');if(new Set(dimensions.map(dimension=>dimension.name)).size!==dimensions.length)throw new Error('Pairwise 维度名称不能重复');if(dimensions.some(dimension=>!dimension.name||!dimension.values.length))throw new Error('每个 Pairwise 维度都需要名称和候选值');if(dimensions.some(dimension=>dimension.name.length>80||dimension.values.length>20||dimension.values.some(value=>value.length>200)))throw new Error('维度名最多 80 字符，每个维度最多 20 个候选值，单值最多 200 字符');const dimensionsByName=new Map(dimensions.map(dimension=>[dimension.name,dimension.values]));for(const rule of[...options.exclusions||[],...options.forced||[]])for(const[name,value]of Object.entries(rule)){if(!dimensionsByName.has(name))throw new Error(`组合规则包含未知维度：${name}`);if(!dimensionsByName.get(name)!.includes(value))throw new Error(`${name} 不包含候选值：${value}`)}const exclusions=options.exclusions||[],uncovered=possiblePairs(dimensions,exclusions),rows:PairwiseRule[]=[];const append=(candidate:PairwiseRule|null)=>{if(!candidate)return;const signature=JSON.stringify(candidate);if(rows.some(row=>JSON.stringify(row)===signature))return;rows.push(candidate);rowPairs(dimensions,candidate).forEach(pair=>uncovered.delete(pair))};for(const forced of options.forced||[]){const candidate=completeCombination(forced,dimensions,exclusions,uncovered);if(!candidate)throw new Error(`强制组合与排除规则冲突：${Object.entries(forced).map(([key,value])=>`${key}=${value}`).join(', ')}`);append(candidate)}while(uncovered.size){const[key]=uncovered,[i,a,j,b]=JSON.parse(key)as[number,string,number,string],candidate=completeCombination({[dimensions[i].name]:a,[dimensions[j].name]:b},dimensions,exclusions,uncovered);if(!candidate){uncovered.delete(key);continue}append(candidate)}if(!rows.length){const candidate=completeCombination({},dimensions,exclusions,uncovered);if(candidate)rows.push(candidate)}return rows}

export const STATE_CHAINS={order:['待支付','已支付','待发货','已发货','已签收'],payment:['创建','处理中','成功'],logistics:['已揽收','运输中','到达网点','派送中','已签收'],quest:['未领取','进行中','已完成','已领奖']}
export type StateErrorMode='none'|'rollback'|'skip'|'duplicate'
export interface StateEventOptions{errorMode?:StateErrorMode;minStayMinutes?:number;maxStayMinutes?:number;terminalIndex?:number}
const seeded=(seed:number)=>{let state=seed>>>0;return()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296}}
export function generateStateEvents(type:keyof typeof STATE_CHAINS,count:number,seed:number,options:boolean|StateEventOptions=false){const chain=STATE_CHAINS[type],config:StateEventOptions=typeof options==='boolean'?{errorMode:options?'rollback':'none'}:options,errorMode=config.errorMode||'none',minStay=Math.max(1,Math.min(10_080,Math.round(config.minStayMinutes??10))),maxStay=Math.max(minStay,Math.min(10_080,Math.round(config.maxStayMinutes??180))),terminal=Math.max(1,Math.min(chain.length-1,config.terminalIndex??chain.length-1)),random=seeded(seed),base=1755129600000-86400000;return Array.from({length:Math.max(1,Math.min(10_000,Math.floor(count)))},(_,entity)=>{const traceId=`trace-${seed}-${entity+1}`,states=[...chain.slice(0,terminal+1)],invalidIndexes=new Set<number>();if(errorMode!=='none'&&entity%4===0){const at=Math.min(2,states.length-1);if(errorMode==='rollback'){states.splice(at,0,states[Math.max(0,at-2)]);invalidIndexes.add(at)}else if(errorMode==='skip'&&states.length>2){states.splice(1,1);invalidIndexes.add(1)}else if(errorMode==='duplicate'){states.splice(at,0,states[Math.max(0,at-1)]);invalidIndexes.add(at)}}let time=base+entity*60000;return states.map((status,index)=>{const stayMinutes=Math.floor(minStay+random()*(maxStay-minStay+1));time+=stayMinutes*60000;return{entityId:`${type}-${entity+1}`,traceId,sequence:index+1,status,occurredAt:new Date(time).toISOString(),stayMinutes:index===0?null:stayMinutes,valid:!invalidIndexes.has(index),mutation:invalidIndexes.has(index)?errorMode:undefined}})}).flat()}
