import type { FieldRule, ProjectSchema, TableSchema } from '../types'
import { ENUM_VALUES } from '../data/enumValues'
import { createZip, GENERATOR_VERSION, sha256Fallback } from './exporters'
import { sortTables } from './modeling'
import { normalizeMockApiOptionsForProject, type MockApiOptions } from './mockApiOptions'

type Dialect='mysql'|'postgres'|'sqlite'
type ContractFile={name:string;content:string}
const encoder=new TextEncoder()
const safeName=(value:string)=>value.replace(/[^A-Za-z0-9_\u4e00-\u9fa5-]/g,'_').slice(0,80)||'mock-schema'
const quote=(value:string,dialect:Dialect)=>dialect==='mysql'?`\`${value.replaceAll('`','``')}\``:`"${value.replaceAll('"','""')}"`
const enumValues=(field:FieldRule)=>field.values?.length?field.values:ENUM_VALUES[field.generator]
const normalizedEnum=(field:FieldRule)=>enumValues(field)?.map(value=>field.dataType==='number'&&Number.isFinite(Number(value))?Number(value):field.dataType==='boolean'&&['true','false'].includes(String(value))?String(value)==='true':value)
const required=(field:FieldRule)=>(field.missing??0)===0&&(field.nullable??0)===0&&!field.condition
const formatFor=(field:FieldRule)=>({email:'email',uuid:'uuid',url:'uri',date:'date',pastDate:'date',futureDate:'date',dateTime:'date-time',ipv4:'ipv4',ipv6:'ipv6'} as Record<string,string>)[field.generator]

export function fieldJsonSchema(field:FieldRule){
  const schema:Record<string,unknown>={title:field.label,type:field.dataType==='date'?'string':field.dataType}
  const format=formatFor(field);if(format)schema.format=format
  const values=normalizedEnum(field);if(values?.length)schema.enum=values
  if(field.min!==undefined)schema.minimum=field.min;if(field.max!==undefined)schema.maximum=field.max;if(field.length!==undefined)schema.maxLength=field.length
  if(field.nullable)schema.type=[schema.type,'null']
  if(field.ref)schema['x-foreign-key']={tableId:field.ref.tableId,field:field.ref.field,strategy:field.ref.strategy??'random',...(field.ref.strategy==='hotspot'?{hotspotPercent:field.ref.hotspotPercent??20}:{})}
  if(field.generator)schema['x-mock-generator']=field.generator
  if(field.formula)schema['x-mock-formula']=field.formula
  if(field.condition)schema['x-mock-condition']=field.condition
  if(field.relationValue)schema['x-mock-relation-value']=field.relationValue
  return schema
}

const tableJsonSchema=(table:TableSchema)=>{const requiredFields=table.fields.filter(required).map(field=>field.name);return{title:table.label,type:'object',additionalProperties:false,properties:Object.fromEntries(table.fields.map(field=>[field.name,fieldJsonSchema(field)])),...(requiredFields.length?{required:requiredFields}:{}),...(table.countByReference?{'x-mock-cardinality':table.countByReference}:{}),...(table.assertions?.length?{'x-mock-assertions':table.assertions}:{})}}

export function toJSONSchema(project:ProjectSchema){return{$schema:'https://json-schema.org/draft/2020-12/schema',$id:`urn:mock-data:${project.id}`,title:project.name,description:project.description,type:'object',properties:Object.fromEntries(project.tables.map(table=>[table.name,{type:'array',items:{$ref:`#/$defs/${table.name}`}}])),$defs:Object.fromEntries(project.tables.map(table=>[table.name,tableJsonSchema(table)])),'x-mock-seed':project.seed,'x-mock-reference-date':project.referenceDate,'x-mock-mode':project.mode,'x-schema-version':project.version}}

export function toOpenAPI(project:ProjectSchema,options?:Partial<MockApiOptions>){
  const behavior=normalizeMockApiOptionsForProject(project,options),traceHeaders={'X-Mock-Request-Id':{description:'稳定请求编号，用于本地请求轨迹定位',schema:{type:'string'}},'X-Mock-Latency':{description:'Mock 实际等待毫秒数',schema:{type:'integer'}}},errorSchema={type:'object',properties:{error:{type:'object',properties:{status:{type:'integer'},message:{type:'string'},index:{type:'integer',minimum:0},field:{type:'string'},rule:{type:'string',enum:['unknown_field','immutable','required','nullable','type','enum','minimum','maximum','max_length','unique']}},required:['status','message']}},required:['error']}
  const wrappedWithMeta=(schema:Record<string,unknown>,meta:Record<string,unknown>):Record<string,unknown>=>behavior.envelope==='plain'?schema:behavior.envelope==='data'?{type:'object',properties:{data:schema},required:['data']}:{type:'object',properties:{data:schema,meta},required:['data','meta']}
  const wrapped=(schema:Record<string,unknown>,list=false):Record<string,unknown>=>wrappedWithMeta(schema,list?{type:'object',properties:{page:{type:'integer'},limit:{type:'integer'},total:{type:'integer'}},required:['page','limit','total']}:{type:'object'})
  const success=(schema:Record<string,unknown>,description:string,status='200',list=false)=>({[status]:{description,headers:{...traceHeaders,...(list?{'X-Total-Count':{schema:{type:'integer'}}}:{})},content:{'application/json':{schema:wrapped(schema,list)}}}})
  const failure=(status:number|string,description:string)=>({[String(status)]:{description,headers:traceHeaders,content:{'application/json':{schema:errorSchema}}}})
  const controlFailure=(status:number|string,description:string)=>({[String(status)]:{description,content:{'application/json':{schema:errorSchema}}}})
  const injectedFor=(method:string,path:string)=>{const rule=behavior.routeOverrides.find(candidate=>candidate.method===method&&candidate.path===path),scenario=rule??behavior;if(scenario.failureRate<=0)return{};return failure(scenario.failureStatus,rule?`${rule.failureMessage}（单路由确定性失败率 ${rule.failureRate}%）`:`按 ${behavior.failureRate}% 确定性注入的网络失败`)}
  const paths=Object.fromEntries(project.tables.flatMap(table=>{
    const primary=table.fields.find(field=>field.primaryKey)??table.fields.find(field=>field.unique)??table.fields[0],schemaRef={$ref:`#/components/schemas/${table.name}`},listSchema={type:'array',items:schemaRef},listPath=`/api/${table.name}`,detailRoute=`${listPath}/:id`,detailPath=`${listPath}/{id}`,batchPath=`${listPath}/_batch`,tag=table.label,pathParameters=[{name:'id',in:'path',required:true,schema:{type:primary.dataType==='number'?'number':'string'}}],bodyProperties=tableJsonSchema(table).properties,createRequired=table.fields.filter(field=>field.name!==primary.name&&required(field)).map(field=>field.name),createBodySchema={type:'object',additionalProperties:false,properties:bodyProperties,...(behavior.validateSchema&&createRequired.length?{required:createRequired}:{})},updateBodySchema={type:'object',additionalProperties:false,properties:Object.fromEntries(table.fields.filter(field=>field.name!==primary.name).map(field=>[field.name,(bodyProperties as Record<string,unknown>)[field.name]]))},hasForeignKeys=table.fields.some(field=>field.ref),isReferenced=project.tables.some(candidate=>candidate.fields.some(field=>field.ref?.tableId===table.id))
    const writeValidation=behavior.validateSchema||behavior.validateForeignKeys&&hasForeignKeys
    const list={get:{tags:[tag],summary:`查询${table.label}列表`,parameters:[['_page','integer'],['_limit','integer'],['_sort','string'],['_order','string'],['q','string'],...table.fields.map(field=>[field.name,field.dataType==='number'?'number':'string'])].map(([name,type])=>({name,in:'query',required:false,schema:{type}})),responses:{...success(listSchema,'分页列表','200',true),...injectedFor('GET',listPath)}},post:{tags:[tag],summary:`新增${table.label}`,requestBody:{required:true,content:{'application/json':{schema:createBodySchema}}},responses:{...success(schemaRef,'创建成功','201'),...failure(400,'请求体不是 JSON 对象'),...failure(409,'主键或唯一字段已存在'),...(writeValidation?failure(422,behavior.validateSchema?'Schema 字段或外键校验失败':'外键指向的父记录不存在'):{}),...injectedFor('POST',listPath)}}}
    const detail={get:{tags:[tag],summary:`查询单条${table.label}`,parameters:pathParameters,responses:{...success(schemaRef,'查询成功'),...failure(404,'记录不存在'),...injectedFor('GET',detailRoute)}},patch:{tags:[tag],summary:`修改${table.label}`,parameters:pathParameters,requestBody:{required:true,content:{'application/json':{schema:updateBodySchema}}},responses:{...success(schemaRef,'修改成功'),...failure(400,'请求体不是 JSON 对象'),...failure(404,'记录不存在'),...failure(409,'唯一字段已存在'),...(writeValidation?failure(422,behavior.validateSchema?'Schema 字段、主键或外键校验失败':'外键指向的父记录不存在'):{}),...injectedFor('PATCH',detailRoute)}},delete:{tags:[tag],summary:`删除${table.label}`,description:behavior.deletePolicy==='cascade'?'递归级联删除所有后代记录':'存在引用当前记录的子记录时拒绝删除',parameters:pathParameters,responses:{...success(schemaRef,'删除成功'),...failure(404,'记录不存在'),...(behavior.deletePolicy==='restrict'&&isReferenced?failure(409,'记录仍被子表引用'):{}),...injectedFor('DELETE',detailRoute)}}}
    const batchUpdateItem={type:'object',additionalProperties:false,required:['id','changes'],properties:{id:{type:primary.dataType==='number'?'number':'string'},changes:updateBodySchema}},batchDeleteBody={oneOf:[{type:'array',minItems:1,maxItems:1000,items:{type:primary.dataType==='number'?'number':'string'}},{type:'object',additionalProperties:false,required:['ids'],properties:{ids:{type:'array',minItems:1,maxItems:1000,items:{type:primary.dataType==='number'?'number':'string'}}}}]},batch={post:{tags:[tag],summary:`原子批量新增${table.label}`,description:'一次创建 1–1,000 条；任一记录失败则整批回滚，错误响应 index 为失败项的从零下标。',requestBody:{required:true,content:{'application/json':{schema:{oneOf:[{type:'array',minItems:1,maxItems:1000,items:createBodySchema},{type:'object',additionalProperties:false,required:['items'],properties:{items:{type:'array',minItems:1,maxItems:1000,items:createBodySchema}}}]}}}},responses:{...success(listSchema,'整批创建成功','201'),...failure(400,'批量请求格式错误或超过上限'),...failure(409,'某条记录主键已存在'),...(writeValidation?failure(422,'某条记录的 Schema 字段或外键校验失败'):{}),...injectedFor('POST',batchPath)}},patch:{tags:[tag],summary:`原子批量修改${table.label}`,description:'接受 1–1,000 个 { id, changes }；ID 重复、记录不存在或外键无效时整批回滚。',requestBody:{required:true,content:{'application/json':{schema:{oneOf:[{type:'array',minItems:1,maxItems:1000,items:batchUpdateItem},{type:'object',additionalProperties:false,required:['items'],properties:{items:{type:'array',minItems:1,maxItems:1000,items:batchUpdateItem}}}]}}}},responses:{...success(listSchema,'整批修改成功'),...failure(400,'批量请求格式错误或超过上限'),...failure(404,'某条记录不存在'),...failure(409,'批次中存在重复 ID'),...(writeValidation?failure(422,'某条记录的 Schema 字段、主键或外键校验失败'):{}),...injectedFor('PATCH',batchPath)}},delete:{tags:[tag],summary:`原子批量删除${table.label}`,description:behavior.deletePolicy==='cascade'?'接受 1–1,000 个 ID，验证全部通过后递归级联删除，返回直接删除记录并在 meta.cascaded 报告级联数量。':'接受 1–1,000 个 ID；任一记录仍被引用时整批不删除。',requestBody:{required:true,content:{'application/json':{schema:batchDeleteBody}}},responses:{...success(listSchema,'整批删除成功'),...failure(400,'批量请求格式错误或超过上限'),...failure(404,'某条记录不存在'),...failure(409,behavior.deletePolicy==='restrict'?'批次中存在重复 ID 或某条记录仍被引用':'批次中存在重复 ID'),...injectedFor('DELETE',batchPath)}}}
    return[[listPath,list],[detailPath,detail],[batchPath,batch]]
  }))
  if(behavior.nestedRoutes)for(const child of project.tables)for(const field of child.fields.filter(candidate=>candidate.ref)){const parent=project.tables.find(table=>table.id===field.ref!.tableId);if(!parent)continue;const duplicate=child.fields.filter(candidate=>candidate.ref?.tableId===parent.id).length>1,route=`/api/${parent.name}/:id/${child.name}${duplicate?`/by-${field.name}`:''}`,path=route.replace(':id','{id}'),childSchema={type:'array',items:{$ref:`#/components/schemas/${child.name}`}},parentPrimary=parent.fields.find(candidate=>candidate.primaryKey)??parent.fields[0];paths[path]={get:{tags:[parent.label,child.label],summary:`查询${parent.label}关联的${child.label}`,description:`通过 ${child.name}.${field.name} 关联`,parameters:[{name:'id',in:'path',required:true,schema:{type:parentPrimary.dataType==='number'?'number':'string'}}],responses:{...success(childSchema,'关联数据','200',true),...failure(404,'父记录不存在'),...injectedFor('GET',route)}}}}
  for(const rule of behavior.routeOverrides){const path=rule.path.replaceAll(':id','{id}'),operation=(paths[path] as Record<string,unknown>|undefined)?.[rule.method.toLowerCase()] as Record<string,unknown>|undefined;if(operation)operation['x-mock-route-override']=rule}
  const summarySchema={type:'object',properties:{status:{type:'string',enum:['ok']},seed:{type:'integer'},tables:{type:'integer'},requests:{type:'integer'},snapshots:{type:'integer'},rows:{type:'object',additionalProperties:{type:'integer'}}},required:['status','seed','tables','requests','snapshots','rows']},controlResponse={description:'Mock 数据状态',content:{'application/json':{schema:wrapped(summarySchema)}}},requestLogSchema={type:'object',properties:{id:{type:'string'},sequence:{type:'integer'},method:{type:'string'},path:{type:'string'},status:{type:'integer'},latencyMs:{type:'integer'},injectedFailure:{type:'boolean'},routeOverride:{type:'string'}},required:['id','sequence','method','path','status','latencyMs','injectedFailure']},snapshotSchema={type:'object',properties:{name:{type:'string'},revision:{type:'integer'},bytes:{type:'integer'},totalRows:{type:'integer'},rows:{type:'object',additionalProperties:{type:'integer'}}},required:['name','revision','bytes','totalRows','rows']},snapshotName={name:'name',in:'path',required:true,schema:{type:'string',minLength:1,maxLength:40,pattern:'^[A-Za-z0-9一-龥_-]+$'}},transactionAlias={type:'string',pattern:'^[A-Za-z][A-Za-z0-9_]{0,29}$'},transactionId={oneOf:[{type:'string'},{type:'number'}],description:'记录主键，或引用前序别名字段的 $alias.field'},transactionResource={type:'string',enum:project.tables.map(table=>table.name)},transactionCreate={type:'object',additionalProperties:false,required:['op','resource','body'],properties:{op:{type:'string',enum:['create']},resource:transactionResource,body:{type:'object',description:'按目标表 Schema 白名单写入；任意值可使用 $alias.field 引用前序结果'},as:transactionAlias}},transactionUpdate={type:'object',additionalProperties:false,required:['op','resource','id','changes'],properties:{op:{type:'string',enum:['update']},resource:transactionResource,id:transactionId,changes:{type:'object',description:'按目标表 Schema 白名单修改；不允许改变主键'},as:transactionAlias}},transactionDelete={type:'object',additionalProperties:false,required:['op','resource','id'],properties:{op:{type:'string',enum:['delete']},resource:transactionResource,id:transactionId,as:transactionAlias}},transactionResult={type:'object',properties:{index:{type:'integer'},op:{type:'string',enum:['create','update','delete']},resource:transactionResource,row:{type:'object'},alias:transactionAlias},required:['index','op','resource','row']}
  paths['/api/__mock/health']={get:{tags:['Mock 控制'],summary:'检查本地 Mock 数据状态',description:'不经过延迟与失败注入。',responses:{'200':controlResponse}}}
  paths['/api/__mock/reset']={post:{tags:['Mock 控制'],summary:'恢复全部初始数据',description:'恢复数据并清空确定性网络场景请求序列、请求轨迹和全部场景快照；不经过延迟与失败注入。',responses:{'200':controlResponse}}}
  paths['/api/__mock/requests']={get:{tags:['Mock 控制'],summary:'查询脱敏请求轨迹',description:'最多保留 500 条，仅含 pathname 与响应元信息，不记录 query、body、Authorization、Cookie 或其他 header。',parameters:[{name:'_limit',in:'query',schema:{type:'integer',minimum:1,maximum:500,default:100}},{name:'method',in:'query',schema:{type:'string',enum:['GET','POST','PATCH','DELETE']}},{name:'status',in:'query',schema:{type:'integer',minimum:100,maximum:599}}],responses:{'200':{description:'倒序请求轨迹',content:{'application/json':{schema:wrappedWithMeta({type:'array',items:requestLogSchema},{type:'object',properties:{total:{type:'integer'},retained:{type:'integer'}},required:['total','retained']})}}}}},delete:{tags:['Mock 控制'],summary:'清空请求轨迹',description:'不改变业务数据和网络场景配置。',responses:{'200':{description:'已清空',content:{'application/json':{schema:wrapped({type:'object',properties:{cleared:{type:'boolean'}},required:['cleared']})}}}}}}
  paths['/api/__mock/snapshots']={get:{tags:['Mock 控制'],summary:'列出场景快照',description:'快照只存在于当前浏览器或测试进程内存中。',responses:{'200':{description:'按修订号倒序的快照',content:{'application/json':{schema:wrappedWithMeta({type:'array',items:snapshotSchema},{type:'object',properties:{total:{type:'integer'},limit:{type:'integer',enum:[10]}},required:['total','limit']})}}}}},post:{tags:['Mock 控制'],summary:'创建或覆盖场景快照',description:'快照名仅允许 1–40 个中英文、数字、下划线或连字符；单个快照最多 5 MiB。',requestBody:{required:true,content:{'application/json':{schema:{type:'object',additionalProperties:false,properties:{name:{type:'string',minLength:1,maxLength:40,pattern:'^[A-Za-z0-9一-龥_-]+$'}},required:['name']}}}},responses:{'200':{description:'同名快照已覆盖',content:{'application/json':{schema:wrappedWithMeta(snapshotSchema,{type:'object',properties:{replaced:{type:'boolean',enum:[true]}},required:['replaced']})}}},'201':{description:'快照已创建',content:{'application/json':{schema:wrappedWithMeta(snapshotSchema,{type:'object',properties:{replaced:{type:'boolean',enum:[false]}},required:['replaced']})}}},...controlFailure(400,'快照名无效'),...controlFailure(409,'已达到 10 个快照上限'),...controlFailure(413,'快照超过 5 MiB')}},delete:{tags:['Mock 控制'],summary:'清空全部场景快照',responses:{'200':{description:'已清空',content:{'application/json':{schema:wrapped({type:'object',properties:{cleared:{type:'integer'}},required:['cleared']})}}}}}}
  paths['/api/__mock/snapshots/{name}/restore']={post:{tags:['Mock 控制'],summary:'恢复场景快照',description:'只恢复整库业务数据，不回退请求轨迹和网络故障序列。',parameters:[snapshotName],responses:{'200':{description:'已恢复',content:{'application/json':{schema:wrapped(snapshotSchema)}}},...controlFailure(404,'快照不存在')}}}
  paths['/api/__mock/snapshots/{name}']={delete:{tags:['Mock 控制'],summary:'删除场景快照',parameters:[snapshotName],responses:{'200':{description:'已删除',content:{'application/json':{schema:wrapped({type:'object',properties:{deleted:{type:'boolean'}},required:['deleted']})}}},...controlFailure(404,'快照不存在')}}}
  paths['/api/__mock/transactions']={post:{tags:['Mock 控制'],summary:'执行原子跨表事务',description:'按顺序解释最多 100 步、1 MiB 的受限 JSON 动作；支持 create/update/delete 和 $alias.field 前向结果引用，不执行 JavaScript。任一步失败会恢复整个数据库。',requestBody:{required:true,content:{'application/json':{schema:{oneOf:[{type:'array',minItems:1,maxItems:100,items:{oneOf:[transactionCreate,transactionUpdate,transactionDelete]}},{type:'object',additionalProperties:false,required:['actions'],properties:{actions:{type:'array',minItems:1,maxItems:100,items:{oneOf:[transactionCreate,transactionUpdate,transactionDelete]}}}}]}}}},responses:{'200':{description:'全部动作已提交',content:{'application/json':{schema:wrappedWithMeta({type:'array',items:transactionResult},{type:'object',properties:{actions:{type:'integer'},aliases:{type:'array',items:{type:'string'}}},required:['actions','aliases']})}}},...controlFailure(400,'事务 JSON、动作、资源、别名或引用无效'),...controlFailure(404,'更新或删除的记录不存在'),...controlFailure(409,'主键、别名或引用删除冲突'),...controlFailure(413,'事务超过 1 MiB'),...controlFailure(422,'外键指向不存在'),...controlFailure(500,'意外运行时错误，整库已回滚')}}}
  return{openapi:'3.1.0',info:{title:`${project.name} Mock API`,description:project.description,version:project.version},servers:[{url:'http://localhost',description:'MSW 本地拦截'}],paths,components:{schemas:Object.fromEntries(project.tables.map(table=>[table.name,tableJsonSchema(table)]))},'x-mock-project':{templateId:project.templateId,seed:project.seed,referenceDate:project.referenceDate,mode:project.mode},'x-mock-api-behavior':behavior}
}

const integerLike=new Set(['autoId','sequence','integer','positiveInt','negativeInt','age','playerLevel','experience','gold','fileSize','timestamp','percentage'])
const sqlType=(field:FieldRule,dialect:Dialect)=>{if(dialect==='sqlite')return field.dataType==='number'?(integerLike.has(field.generator)?'INTEGER':'REAL'):field.dataType==='boolean'?'INTEGER':'TEXT';if(field.dataType==='number'){if(integerLike.has(field.generator))return'BIGINT';return dialect==='mysql'?`DECIMAL(20, ${field.precision??2})`:`NUMERIC(20, ${field.precision??2})`}if(field.dataType==='boolean')return dialect==='mysql'?'TINYINT(1)':'BOOLEAN';if(field.dataType==='date')return dialect==='mysql'?'DATETIME':'TIMESTAMPTZ';if(field.dataType==='object')return dialect==='mysql'?'JSON':'JSONB';if(field.length&&field.length<=4000)return`VARCHAR(${Math.max(1,field.length)})`;return'TEXT'}

export function toDDL(project:ProjectSchema,dialect:Dialect){
  const lines=[`-- ${project.name} · Schema ${project.version} · generated by Mock造数工具`,`-- Dialect: ${dialect}`]
  for(const table of sortTables(project.tables)){const columns=table.fields.map(field=>{const constraints=[required(field)?'NOT NULL':'',field.primaryKey?'PRIMARY KEY':'',field.unique&&!field.primaryKey?'UNIQUE':''].filter(Boolean).join(' ');return`  ${quote(field.name,dialect)} ${sqlType(field,dialect)}${constraints?` ${constraints}`:''}`}),foreignKeys=table.fields.filter(field=>field.ref).map(field=>{const target=project.tables.find(candidate=>candidate.id===field.ref!.tableId);return target?`  FOREIGN KEY (${quote(field.name,dialect)}) REFERENCES ${quote(target.name,dialect)} (${quote(field.ref!.field,dialect)})`:''}).filter(Boolean);lines.push(`CREATE TABLE IF NOT EXISTS ${quote(table.name,dialect)} (\n${[...columns,...foreignKeys].join(',\n')}\n);`)}return`${lines.join('\n\n')}\n`
}

const typeName=(value:string)=>value.split(/[^A-Za-z0-9]+/).filter(Boolean).map(part=>part[0].toUpperCase()+part.slice(1)).join('')||'MockRecord'
const tsType=(field:FieldRule)=>{const values=normalizedEnum(field);let base=values?.length&&values.length<=50?values.map(value=>JSON.stringify(value)).join(' | '):field.dataType==='number'?'number':field.dataType==='boolean'?'boolean':field.dataType==='object'?'Record<string, unknown>':'string';if(field.nullable||field.condition?.otherwise==='null')base+=` | null`;return base}
export function toTypeScript(project:ProjectSchema){return`${project.tables.map(table=>`/** ${table.label} · 默认 ${table.count} 条 */\nexport interface ${typeName(table.name)} {\n${table.fields.map(field=>`  /** ${field.label}${field.ref?` · FK → ${field.ref.tableId}.${field.ref.field}`:''} */\n  ${field.name}${(field.missing??0)>0||field.condition?.otherwise==='omit'?'?':''}: ${tsType(field)};`).join('\n')}\n}`).join('\n\n')}\n`}

export function relationMarkdown(project: ProjectSchema) {
  const labels = { random:'种子随机', roundRobin:'轮询均匀', hotspot:'热点 80/20', oneToOne:'严格一对一' }
  const relations = project.tables.flatMap(table => table.fields.filter(field => field.ref).map(field => {
    const target = project.tables.find(candidate => candidate.id === field.ref!.tableId)
    const strategy = field.ref!.strategy ?? 'random'
    const cardinality = table.countByReference?.fieldId === field.id ? table.countByReference : null
    const description = cardinality ? `每个父记录 ${cardinality.min}–${cardinality.max} 条` : `${labels[strategy]}${strategy === 'hotspot' ? `，热点池 ${field.ref!.hotspotPercent ?? 20}%` : ''}`
    return `- \`${table.name}.${field.name}\` → \`${target?.name ?? field.ref!.tableId}.${field.ref!.field}\`（${description}）`
  }))
  const calculations = project.tables.flatMap(table => table.fields.filter(field => field.relationValue).map(field => {
    const rule = field.relationValue!
    if (rule.kind === 'aggregate') return `- \`${table.name}.${field.name}\` = ${rule.operation.toUpperCase()}(\`${rule.sourceTableId}.${rule.expression}\`)（通过 \`${rule.sourceForeignKey}\` 分组，小数精度 ${rule.precision ?? 2}）`
    return `- \`${table.name}.${field.name}\` ← \`${rule.sourceTableId}.${rule.sourceField}\`（\`${field.name}\` 所在行的 \`${rule.localForeignKey}\` = \`${rule.sourceKey}\`）`
  }))
  const assertions = project.tables.flatMap(table => (table.assertions ?? []).map(assertion => `- **${table.label}.${assertion.name}**：\`${assertion.expression}\`（${assertion.severity === 'error' ? '失败' : '警告'}；${assertion.message}）`))
  const tables = sortTables(project.tables).map((table,index) => `${index + 1}. **${table.label}**（\`${table.name}\`）：${table.fields.length} 字段，${table.countByReference ? `按父记录生成 ${table.countByReference.min}–${table.countByReference.max} 条子数据` : `默认 ${table.count} 条`}`).join('\n')
  return `# ${project.name} Schema 关系说明\n\n- Schema 版本：${project.version}\n- 随机种子：${project.seed}\n- 时间基准：${project.referenceDate ?? '兼容旧项目默认值'}\n- 造数模式：${project.mode}\n- 数据表：${project.tables.length}\n- 字段：${project.tables.reduce((sum,table)=>sum+table.fields.length,0)}\n\n## 数据表\n\n${tables}\n\n## 外键关系\n\n${relations.length ? relations.join('\n') : '- 当前项目没有外键关系。'}\n\n## 跨表计算\n\n${calculations.length ? calculations.join('\n') : '- 当前项目没有跨表计算规则。'}\n\n## 业务断言\n\n${assertions.length ? assertions.join('\n') : '- 当前项目没有业务断言。'}\n`
}

export function schemaContractFiles(project:ProjectSchema):ContractFile[]{return[
  {name:'json-schema.json',content:JSON.stringify(toJSONSchema(project),null,2)},
  {name:'openapi.json',content:JSON.stringify(toOpenAPI(project),null,2)},
  {name:'types.ts',content:toTypeScript(project)},
  {name:'ddl/mysql.sql',content:toDDL(project,'mysql')},
  {name:'ddl/postgres.sql',content:toDDL(project,'postgres')},
  {name:'ddl/sqlite.sql',content:toDDL(project,'sqlite')},
  {name:'RELATIONS.md',content:relationMarkdown(project)},
]}

const digest=async(value:string)=>{const bytes=encoder.encode(value);if(globalThis.crypto?.subtle)return[...new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256',bytes))].map(byte=>byte.toString(16).padStart(2,'0')).join('');return sha256Fallback(bytes)}
export async function createSchemaContractPackage(project:ProjectSchema){const createdAt=new Date(),files=schemaContractFiles(project),manifest={manifestVersion:1,kind:'schema-contract',projectName:project.name,schemaVersion:project.version,generatorVersion:GENERATOR_VERSION,randomSeed:project.seed,referenceDate:project.referenceDate,packagedAt:createdAt.toISOString(),files:await Promise.all(files.map(async file=>({name:file.name,bytes:encoder.encode(file.content).length,sha256:await digest(file.content)})))},zip=createZip([...files,{name:'manifest.json',content:JSON.stringify(manifest,null,2)}],createdAt);return{blob:new Blob([zip],{type:'application/zip'}),filename:`${safeName(project.name)}_schema.zip`,manifest}}
export async function exportSchemaContract(project:ProjectSchema){const result=await createSchemaContractPackage(project),url=URL.createObjectURL(result.blob),anchor=document.createElement('a');anchor.href=url;anchor.download=result.filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return result}
