import type { DataType, FieldRule, ProjectSchema, TableSchema } from '../types'
import { MAX_CONFIG_BYTES } from './projectConfig'

export interface ImportPreview { source:'openapi'|'json'|'sql'|'typescript'; project:ProjectSchema; warnings:string[] }

const MAX_TABLES=50,MAX_FIELDS=200
const DEFAULT_REFERENCE_DATE='2026-08-14T00:00:00.000Z'
const safeName=(value:string,fallback:string)=>{const normalized=value.trim().replace(/[^A-Za-z0-9_]/g,'_').replace(/^([^A-Za-z_])/,'_$1').slice(0,80);return normalized||fallback}
const label=(value:string)=>value.replace(/[_-]+/g,' ').trim().slice(0,80)||'未命名'
const id=()=>`f_${Date.now()}_${Math.random().toString(36).slice(2,8)}`
const lower=(value:string)=>value.toLowerCase()

function inferGenerator(name:string,type:DataType,format?:string){
  const key=lower(name),formats:Record<string,string>={uuid:'uuid',email:'email',uri:'url',url:'url',date:'date','date-time':'dateTime',ipv4:'ipv4',ipv6:'ipv6',hostname:'domain'}
  if(format&&formats[format])return formats[format]
  if(/(^|_)(id)$/.test(key)||key==='id')return type==='string'?'uuid':'autoId'
  if(/phone|mobile/.test(key))return'phone';if(/email/.test(key))return'email';if(/name/.test(key))return'chineseName';if(/address/.test(key))return'address';if(/city/.test(key))return'city';if(/province/.test(key))return'province'
  if(/amount|price|fee|balance|total/.test(key))return'amount';if(/status|state/.test(key))return'customEnum';if(/url|link/.test(key))return'url';if(/ip/.test(key))return'ipv4';if(/time|date|created|updated|expired/.test(key))return type==='number'?'timestamp':'dateTime'
  return type==='number'?'integer':type==='boolean'?'boolean':type==='date'?'dateTime':'randomString'
}

function schemaType(schema:Record<string,unknown>):DataType {const type=Array.isArray(schema.type)?schema.type.find(value=>value!=='null'):schema.type;if(type==='integer'||type==='number')return'number';if(type==='boolean')return'boolean';if(type==='object'||type==='array')return'object';if(schema.format==='date'||schema.format==='date-time')return'date';return'string'}

function schemaField(name:string,schema:Record<string,unknown>,required:boolean):FieldRule {
  const dataType=schemaType(schema),format=typeof schema.format==='string'?schema.format:undefined,values=Array.isArray(schema.enum)?schema.enum.slice(0,10_000).map(String):undefined,generator=values?.length?'customEnum':dataType==='object'?'fixed':inferGenerator(name,dataType,format)
  const field:FieldRule={id:id(),name:safeName(name,'field'),label:typeof schema.title==='string'?schema.title.slice(0,80):label(name),generator,dataType,missing:required?0:15}
  if(dataType==='object')field.fixedValue=schema.type==='array'?'[]':'{}'
  if(values?.length)field.values=values;if(typeof schema.minimum==='number')field.min=schema.minimum;if(typeof schema.maximum==='number')field.max=schema.maximum;if(typeof schema.maxLength==='number')field.length=Math.min(10_000,Math.max(0,schema.maxLength));if(schema.nullable===true)field.nullable=10
  if(field.name==='id'||field.name.endsWith('_id')&&schema['x-primary-key']===true){field.primaryKey=true;field.unique=true}
  return field
}

function objectTable(name:string,schema:Record<string,unknown>,index:number):TableSchema {
  const properties=schema.properties&&typeof schema.properties==='object'&&!Array.isArray(schema.properties)?schema.properties as Record<string,unknown>:{}
  const required=new Set(Array.isArray(schema.required)?schema.required.map(String):[]),entries=Object.entries(properties).slice(0,MAX_FIELDS)
  const fields=entries.map(([fieldName,value])=>schemaField(fieldName,value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{},required.has(fieldName)))
  if(!fields.length)fields.push({id:id(),name:'id',label:'ID',generator:'autoId',dataType:'number',primaryKey:true,unique:true})
  const primary=fields.find(field=>field.name==='id')||fields.find(field=>field.name.endsWith('Id')||field.name.endsWith('_id'));if(primary){primary.primaryKey=true;primary.unique=true}
  return{id:`imported_${index}_${safeName(name,'table').toLowerCase()}`,name:safeName(name,`table_${index+1}`).toLowerCase(),label:typeof schema.title==='string'?schema.title.slice(0,80):label(name),count:20,fields}
}

function connectIdReferences(tables:TableSchema[]){const aliases=new Map<string,TableSchema>();tables.forEach(table=>{for(const value of [table.name,table.name.replace(/s$/,''),table.id.split('_').slice(2).join('_')])aliases.set(lower(value),table)});tables.forEach(table=>table.fields.forEach(field=>{if(field.primaryKey)return;const match=field.name.match(/^(.+?)(?:_?id)$/i);if(!match)return;const target=aliases.get(lower(match[1]))||aliases.get(`${lower(match[1])}s`);const primary=target?.fields.find(candidate=>candidate.primaryKey);if(target&&primary&&target.id!==table.id){field.ref={tableId:target.id,field:primary.name};field.dataType=primary.dataType;field.generator=primary.generator}}))}

const mergeOpenApiSchemas=(base:Record<string,unknown>,extra:Record<string,unknown>)=>{const properties={...(base.properties&&typeof base.properties==='object'&&!Array.isArray(base.properties)?base.properties as Record<string,unknown>:{}),...(extra.properties&&typeof extra.properties==='object'&&!Array.isArray(extra.properties)?extra.properties as Record<string,unknown>:{})},required=[...new Set([...(Array.isArray(base.required)?base.required.map(String):[]),...(Array.isArray(extra.required)?extra.required.map(String):[])])];return{...base,...extra,...(Object.keys(properties).length?{properties}:{}),...(required.length?{required}:{})}}
const refName=(ref:string)=>{const prefix='#/components/schemas/';if(!ref.startsWith(prefix))return null;return ref.slice(prefix.length).replaceAll('~1','/').replaceAll('~0','~')}
function resolveOpenApiSchema(schema:Record<string,unknown>,schemas:Record<string,unknown>,warnings:string[],trail:string[]=[],depth=0):Record<string,unknown>{
  if(depth>20){warnings.push(`本地 $ref 展开超过 20 层，已在 ${trail.join(' → ')} 处停止`);return{type:'object'}}
  let resolved={...schema}
  if(typeof resolved.$ref==='string'){const name=refName(resolved.$ref);if(!name)throw new Error(`拒绝外部 $ref：${resolved.$ref}`);if(trail.includes(name)){warnings.push(`检测到循环 $ref：${[...trail,name].join(' → ')}`);return{type:'object',title:name,'x-mock-ref-name':name}}const target=schemas[name];if(!target||typeof target!=='object'||Array.isArray(target))throw new Error(`本地 $ref 目标不存在：${resolved.$ref}`);const{$ref:_,...overlay}=resolved;resolved={...mergeOpenApiSchemas(resolveOpenApiSchema(target as Record<string,unknown>,schemas,warnings,[...trail,name],depth+1),overlay),'x-mock-ref-name':name}}
  if(Array.isArray(resolved.allOf)){const{allOf,...rest}=resolved;resolved=(allOf as unknown[]).reduce<Record<string,unknown>>((result,item)=>item&&typeof item==='object'&&!Array.isArray(item)?mergeOpenApiSchemas(result,resolveOpenApiSchema(item as Record<string,unknown>,schemas,warnings,trail,depth+1)):result,rest)}
  if(resolved.properties&&typeof resolved.properties==='object'&&!Array.isArray(resolved.properties))resolved.properties=Object.fromEntries(Object.entries(resolved.properties as Record<string,unknown>).map(([name,value])=>[name,value&&typeof value==='object'&&!Array.isArray(value)?resolveOpenApiSchema(value as Record<string,unknown>,schemas,warnings,trail,depth+1):value]))
  if(resolved.items&&typeof resolved.items==='object'&&!Array.isArray(resolved.items))resolved.items=resolveOpenApiSchema(resolved.items as Record<string,unknown>,schemas,warnings,trail,depth+1)
  return resolved
}

function fromOpenApi(document:Record<string,unknown>):ImportPreview {
  const components=document.components&&typeof document.components==='object'?document.components as Record<string,unknown>:undefined,schemas=components?.schemas&&typeof components.schemas==='object'&&!Array.isArray(components.schemas)?components.schemas as Record<string,unknown>:{}
  const entries=Object.entries(schemas).slice(0,MAX_TABLES),warnings:string[]=[];if(Object.keys(schemas).length>MAX_TABLES)warnings.push(`仅导入前 ${MAX_TABLES} 个 components.schemas`)
  const resolvedEntries=entries.filter(([,schema])=>schema&&typeof schema==='object'&&!Array.isArray(schema)).map(([name,schema])=>[name,resolveOpenApiSchema(schema as Record<string,unknown>,schemas,warnings,[name])] as const),tables=resolvedEntries.map(([name,schema],index)=>objectTable(name,schema,index));if(!tables.length)throw new Error('OpenAPI 文档中没有可导入的 components.schemas 对象')
  const bySchema=new Map(resolvedEntries.map(([name],index)=>[name,tables[index]]));resolvedEntries.forEach(([sourceName,schema],index)=>{const source=tables[index],properties=schema.properties&&typeof schema.properties==='object'&&!Array.isArray(schema.properties)?schema.properties as Record<string,unknown>:{};Object.entries(properties).forEach(([fieldName,value])=>{if(!value||typeof value!=='object'||Array.isArray(value))return;const property=value as Record<string,unknown>,direct=typeof property['x-mock-ref-name']==='string'?property['x-mock-ref-name'] as string:undefined,item=property.items&&typeof property.items==='object'&&!Array.isArray(property.items)?property.items as Record<string,unknown>:undefined,arrayTarget=typeof item?.['x-mock-ref-name']==='string'?item['x-mock-ref-name'] as string:undefined;if(arrayTarget){warnings.push(`${sourceName}.${fieldName} 是 ${arrayTarget} 数组关系，保留为嵌套数组字段`);return}if(!direct)return;const target=bySchema.get(direct),primary=target?.fields.find(field=>field.primaryKey),field=source.fields.find(candidate=>candidate.name===safeName(fieldName,'field'));if(target&&primary&&field&&target.id!==source.id){field.ref={tableId:target.id,field:primary.name};field.dataType=primary.dataType;field.generator=primary.generator;field.fixedValue=undefined}else warnings.push(`${sourceName}.${fieldName} 引用 ${direct}，但目标没有可用主键，保留为对象字段`)})})
  connectIdReferences(tables);const info=document.info&&typeof document.info==='object'?document.info as Record<string,unknown>:{};return{source:'openapi',warnings,project:{id:`project_${Date.now()}`,name:typeof info.title==='string'?`${info.title.slice(0,80)} Mock 数据`:'OpenAPI Mock 数据',templateId:'imported-openapi',description:'从 OpenAPI 3.x JSON Schema 本地推断生成',seed:20250814,referenceDate:DEFAULT_REFERENCE_DATE,mode:'random',version:typeof info.version==='string'?info.version.slice(0,20):'1.0',tables}}
}

function valueSchema(values:unknown[]):Record<string,unknown>{const nonNull=values.find(value=>value!==null&&value!==undefined);if(Array.isArray(nonNull))return{type:'array'};if(nonNull&&typeof nonNull==='object'){const records=values.filter(value=>value&&typeof value==='object'&&!Array.isArray(value)) as Record<string,unknown>[],keys=[...new Set(records.flatMap(Object.keys))];return{type:'object',properties:Object.fromEntries(keys.map(key=>[key,valueSchema(records.map(record=>record[key]))])),required:keys.filter(key=>records.every(record=>record[key]!==undefined))}}if(typeof nonNull==='number')return{type:Number.isInteger(nonNull)?'integer':'number'};if(typeof nonNull==='boolean')return{type:'boolean'};return{type:'string'}}

function fromJson(value:unknown):ImportPreview {
  let tables:TableSchema[]=[]
  if(Array.isArray(value)){if(!value.length||!value.some(item=>item&&typeof item==='object'&&!Array.isArray(item)))throw new Error('JSON 数组至少需要一个对象元素');tables=[objectTable('records',valueSchema(value),0)];tables[0].count=Math.min(100_000,Math.max(20,value.length))}
  else if(value&&typeof value==='object'){const record=value as Record<string,unknown>,arrays=Object.entries(record).filter(([,item])=>Array.isArray(item)&&(item as unknown[]).some(entry=>entry&&typeof entry==='object'&&!Array.isArray(entry)));if(arrays.length)tables=arrays.slice(0,MAX_TABLES).map(([name,items],index)=>{const table=objectTable(name,valueSchema(items as unknown[]),index);table.count=Math.min(100_000,Math.max(20,(items as unknown[]).length));return table});else tables=[objectTable('records',valueSchema([record]),0)]}
  else throw new Error('JSON 根节点必须是对象或对象数组')
  connectIdReferences(tables);return{source:'json',warnings:[],project:{id:`project_${Date.now()}`,name:'JSON 样例 Mock 数据',templateId:'imported-json',description:'从 JSON 样例结构本地推断生成',seed:20250814,referenceDate:DEFAULT_REFERENCE_DATE,mode:'random',version:'1.0',tables}}
}

const unquote=(value:string)=>value.trim().replace(/^[`"[]|[`"\]]$/g,'').split('.').pop()||value
const splitSqlItems=(body:string)=>{const items:string[]=[];let current='',depth=0,quote='';for(let index=0;index<body.length;index++){const char=body[index];if(quote){current+=char;if(char===quote&&body[index-1]!=='\\')quote='';continue}if(["'",'"','`'].includes(char)){quote=char;current+=char;continue}if(char==='(')depth++;else if(char===')')depth--;if(char===','&&depth===0){if(current.trim())items.push(current.trim());current=''}else current+=char}if(current.trim())items.push(current.trim());return items}
const identifierList=(value:string)=>value.split(',').map(item=>unquote(item.trim())).filter(Boolean)
const sqlDataType=(definition:string):{dataType:DataType;generator:string;length?:number;precision?:number}=>{const type=definition.trim().split(/\s+/)[0].toLowerCase(),name=type.replace(/\(.*/,''),size=type.match(/\((\d+)(?:\s*,\s*(\d+))?\)/);if(/^(bool|boolean)$/.test(name)||name==='tinyint'&&size?.[1]==='1')return{dataType:'boolean',generator:'boolean'};if(/^(tinyint|smallint|mediumint|int|integer|bigint|serial|bigserial)$/.test(name))return{dataType:'number',generator:'integer'};if(/^(decimal|numeric|real|double|float|money)$/.test(name))return{dataType:'number',generator:'float',precision:size?.[2]?Number(size[2]):2};if(/date|time/.test(name))return{dataType:'date',generator:name==='date'?'date':'dateTime'};if(/json|array/.test(name)||type.endsWith('[]'))return{dataType:'object',generator:'fixed'};if(/char|text|clob|enum|uuid|inet/.test(name)){const format=/uuid/.test(name)?'uuid':/inet/.test(name)?'ipv4':undefined;return{dataType:'string',generator:format||'randomString',length:size?.[1]?Math.min(10_000,Number(size[1])):undefined}}return{dataType:'string',generator:'randomString'}}

function sqlStatements(raw:string){const clean=raw.replace(/\/\*[\s\S]*?\*\//g,' ').replace(/--[^\r\n]*/g,' '),statements:Array<{name:string;body:string}>=[];const regex=/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?((?:[`"\[]?[A-Za-z_][\w$]*[`"\]]?\.)?[`"\[]?[A-Za-z_][\w$]*[`"\]]?)\s*\(/ig;let match:RegExpExecArray|null
  while((match=regex.exec(clean))&&statements.length<MAX_TABLES){let depth=1,index=regex.lastIndex,quote='';for(;index<clean.length&&depth>0;index++){const char=clean[index];if(quote){if(char===quote&&clean[index-1]!=='\\')quote='';continue}if(["'",'"','`'].includes(char)){quote=char;continue}if(char==='(')depth++;else if(char===')')depth--}if(depth!==0)throw new Error(`数据表 ${unquote(match[1])} 的括号没有闭合`);statements.push({name:unquote(match[1]),body:clean.slice(regex.lastIndex,index-1)});regex.lastIndex=index}
  return{statements,truncated:(clean.match(/CREATE\s+TABLE\b/ig)||[]).length>MAX_TABLES}
}

function fromSql(raw:string):ImportPreview {
  const{statements,truncated}=sqlStatements(raw);if(!statements.length)throw new Error('没有识别到 CREATE TABLE 语句')
  const pendingRefs:Array<{table:string;field:string;targetTable:string;targetField:string}>=[],tables=statements.map((statement,index)=>{const fields:FieldRule[]=[],primary=new Set<string>(),unique=new Set<string>();for(const item of splitSqlItems(statement.body)){const normalized=item.trim();let match=normalized.match(/^(?:CONSTRAINT\s+[^\s]+\s+)?PRIMARY\s+KEY\s*\(([^)]+)\)/i);if(match){identifierList(match[1]).forEach(name=>primary.add(name));continue}match=normalized.match(/^(?:CONSTRAINT\s+[^\s]+\s+)?UNIQUE(?:\s+KEY|\s+INDEX)?(?:\s+[^\s(]+)?\s*\(([^)]+)\)/i);if(match){identifierList(match[1]).forEach(name=>unique.add(name));continue}match=normalized.match(/^(?:CONSTRAINT\s+[^\s]+\s+)?FOREIGN\s+KEY\s*\(([^)]+)\)\s+REFERENCES\s+([^\s(]+)\s*\(([^)]+)\)/i);if(match){const sources=identifierList(match[1]),targets=identifierList(match[3]);sources.forEach((field,refIndex)=>pendingRefs.push({table:statement.name,field,targetTable:unquote(match![2]),targetField:targets[refIndex]||targets[0]}));continue}if(/^(CHECK|KEY|INDEX|CONSTRAINT)\b/i.test(normalized))continue;const column=normalized.match(/^([`"\[]?[A-Za-z_][\w$]*[`"\]]?)\s+(.+)$/s);if(!column)continue;const name=unquote(column[1]),definition=column[2],type=sqlDataType(definition),generator=inferGenerator(name,type.dataType,type.generator==='uuid'?'uuid':undefined),field:FieldRule={id:id(),name:safeName(name,`field_${fields.length+1}`),label:label(name),generator:type.generator==='randomString'?generator:type.generator,dataType:type.dataType,missing:/\bNOT\s+NULL\b/i.test(definition)?0:15};if(type.length)field.length=type.length;if(type.precision!==undefined)field.precision=type.precision;if(/\bPRIMARY\s+KEY\b/i.test(definition)){field.primaryKey=true;field.unique=true}if(/\bUNIQUE\b/i.test(definition))field.unique=true;const enumMatch=definition.match(/\bENUM\s*\(([^)]+)\)/i);if(enumMatch){field.generator='customEnum';field.values=splitSqlItems(enumMatch[1]).map(value=>value.replace(/^['"]|['"]$/g,''))}const ref=definition.match(/\bREFERENCES\s+([^\s(]+)\s*\(([^)]+)\)/i);if(ref)pendingRefs.push({table:statement.name,field:name,targetTable:unquote(ref[1]),targetField:unquote(ref[2])});fields.push(field)}for(const field of fields){if(primary.has(field.name)){field.primaryKey=true;field.unique=true}if(unique.has(field.name))field.unique=true}if(!fields.length)throw new Error(`数据表 ${statement.name} 没有可识别的字段`);return{id:`sql_${index}_${safeName(statement.name,'table').toLowerCase()}`,name:safeName(statement.name,`table_${index+1}`).toLowerCase(),label:label(statement.name),count:20,fields}})
  const byName=new Map(tables.map(table=>[lower(table.name),table]));for(const ref of pendingRefs){const table=byName.get(lower(ref.table)),target=byName.get(lower(ref.targetTable)),field=table?.fields.find(candidate=>lower(candidate.name)===lower(ref.field)),targetField=target?.fields.find(candidate=>lower(candidate.name)===lower(ref.targetField));if(table&&target&&field&&targetField){field.ref={tableId:target.id,field:targetField.name};field.dataType=targetField.dataType;field.generator=targetField.generator}}
  return{source:'sql',warnings:truncated?[`仅导入前 ${MAX_TABLES} 个 CREATE TABLE 语句`]:[],project:{id:`project_${Date.now()}`,name:'SQL DDL Mock 数据',templateId:'imported-sql',description:'从 SQL CREATE TABLE 本地解析生成',seed:20250814,referenceDate:DEFAULT_REFERENCE_DATE,mode:'random',version:'1.0',tables}}
}

interface TypeDeclaration { name:string; body:string }
const stripTypeScriptComments=(raw:string)=>raw.replace(/\/\*[\s\S]*?\*\//g,' ').replace(/(^|[^:])\/\/[^\r\n]*/g,'$1 ')
const typeDeclarations=(raw:string)=>{const clean=stripTypeScriptComments(raw),declarations:TypeDeclaration[]=[];const regex=/(?:^|[;\n])\s*(?:export\s+)?(?:declare\s+)?(?:interface\s+([A-Za-z_$][\w$]*)(?:\s+extends\s+[^\{]+)?|type\s+([A-Za-z_$][\w$]*)\s*=)\s*\{/g;let match:RegExpExecArray|null
  while((match=regex.exec(clean))&&declarations.length<MAX_TABLES){let depth=1,index=regex.lastIndex,quote='';for(;index<clean.length&&depth>0;index++){const char=clean[index];if(quote){if(char===quote&&clean[index-1]!=='\\')quote='';continue}if(["'",'"','`'].includes(char)){quote=char;continue}if(char==='{')depth++;else if(char==='}')depth--}if(depth!==0)throw new Error(`类型 ${match[1]||match[2]} 的大括号没有闭合`);declarations.push({name:match[1]||match[2],body:clean.slice(regex.lastIndex,index-1)});regex.lastIndex=index}return{declarations,truncated:(clean.match(/\b(?:interface|type)\s+[A-Za-z_$][\w$]*(?:\s+extends\s+[^\{=]+)?\s*(?:=\s*)?\{/g)||[]).length>MAX_TABLES}}
const splitTypeMembers=(body:string)=>{const members:string[]=[];let current='',curly=0,square=0,round=0,angle=0,quote='';for(let index=0;index<body.length;index++){const char=body[index];if(quote){current+=char;if(char===quote&&body[index-1]!=='\\')quote='';continue}if(["'",'"','`'].includes(char)){quote=char;current+=char;continue}if(char==='{')curly++;else if(char==='}')curly--;else if(char==='[')square++;else if(char===']')square--;else if(char==='(')round++;else if(char===')')round--;else if(char==='<')angle++;else if(char==='>')angle=Math.max(0,angle-1);if((char===';'||char===','||char==='\n')&&curly===0&&square===0&&round===0&&angle===0){if(current.trim())members.push(current.trim());current=''}else current+=char}if(current.trim())members.push(current.trim());return members}
const literalValues=(type:string)=>{const parts=type.split('|').map(part=>part.trim()).filter(part=>!['null','undefined'].includes(part));if(!parts.length||!parts.every(part=>/^(?:'([^']*)'|"([^"]*)"|-?\d+(?:\.\d+)?|true|false)$/.test(part)))return undefined;return parts.map(part=>{const string=part.match(/^(?:'([^']*)'|"([^"]*)")$/);return string?(string[1]??string[2]):part})}
const typeField=(name:string,rawType:string,optional:boolean):{field:FieldRule;referenceType?:string}=>{const nullable=/(^|\|)\s*null\s*(\||$)/.test(rawType),type=rawType.replace(/\|\s*(?:null|undefined)\b/g,'').trim(),array=type.match(/^(?:Readonly)?Array\s*<([\s\S]+)>$/)||type.match(/^([\s\S]+)\[\]$/),values=literalValues(type),reference=/^[A-Z_$][\w$]*$/.test(type)?type:undefined;let dataType:DataType='string',generator='randomString',fixedValue:string|undefined
  if(values?.length){generator='customEnum';dataType=values.every(value=>!Number.isNaN(Number(value)))?'number':'string'}else if(/^(number|bigint)$/.test(type)){dataType='number';generator=inferGenerator(name,dataType)}else if(type==='boolean'){dataType='boolean';generator='boolean'}else if(type==='Date'){dataType='date';generator=inferGenerator(name,dataType,'date-time')}else if(array||/^\{|^(?:Record|Map|Set|object|unknown|any)\b/.test(type)){dataType='object';generator='fixed';fixedValue=array?'[]':'{}'}else if(reference){dataType='object';generator='fixed';fixedValue='{}'}else generator=inferGenerator(name,dataType)
  const field:FieldRule={id:id(),name:safeName(name,'field'),label:label(name),generator,dataType,missing:optional?15:0};if(nullable)field.nullable=10;if(values?.length)field.values=values.slice(0,10_000);if(fixedValue!==undefined)field.fixedValue=fixedValue;if(field.name==='id'){field.primaryKey=true;field.unique=true}
  return{field,referenceType:reference}
}

function fromTypeScript(raw:string):ImportPreview {
  const{declarations,truncated}=typeDeclarations(raw);if(!declarations.length)throw new Error('没有识别到 TypeScript interface 或对象 type 声明')
  const warnings:string[]=truncated?[`仅导入前 ${MAX_TABLES} 个 TypeScript 类型`]:[],references:Array<{table:string;field:FieldRule;target:string}>=[],tables=declarations.map((declaration,index)=>{const fields:FieldRule[]=[];for(const member of splitTypeMembers(declaration.body).slice(0,MAX_FIELDS)){if(/^\[/.test(member)||/^\(/.test(member)){warnings.push(`${declaration.name} 中的索引签名或方法已忽略`);continue}const match=member.match(/^(?:readonly\s+)?(?:['"]([^'"]+)['"]|([A-Za-z_$][\w$]*))\s*(\?)?\s*:\s*([\s\S]+)$/);if(!match){if(member.trim())warnings.push(`${declaration.name} 中无法识别成员：${member.slice(0,60)}`);continue}const fieldName=match[1]||match[2],parsed=typeField(fieldName,match[4].trim(),!!match[3]);fields.push(parsed.field);if(parsed.referenceType)references.push({table:declaration.name,field:parsed.field,target:parsed.referenceType})}if(!fields.length)fields.push({id:id(),name:'id',label:'ID',generator:'autoId',dataType:'number',primaryKey:true,unique:true});const primary=fields.find(field=>field.name==='id');if(primary){primary.primaryKey=true;primary.unique=true}return{id:`ts_${index}_${safeName(declaration.name,'table').toLowerCase()}`,name:safeName(declaration.name,`table_${index+1}`).toLowerCase(),label:label(declaration.name),count:20,fields}})
  const byType=new Map(declarations.map((declaration,index)=>[declaration.name,tables[index]]));for(const reference of references){const target=byType.get(reference.target),targetPrimary=target?.fields.find(field=>field.primaryKey);if(!target||!targetPrimary){warnings.push(`${reference.table}.${reference.field.name} 引用了未导入类型 ${reference.target}，保留为对象字段`);continue}reference.field.ref={tableId:target.id,field:targetPrimary.name};reference.field.dataType=targetPrimary.dataType;reference.field.generator=targetPrimary.generator;reference.field.fixedValue=undefined;warnings.push(`${reference.table}.${reference.field.name} 已按 ${reference.target}.${targetPrimary.name} 建立外键`)}connectIdReferences(tables)
  return{source:'typescript',warnings,project:{id:`project_${Date.now()}`,name:'TypeScript 类型 Mock 数据',templateId:'imported-typescript',description:'从 TypeScript interface/type 本地静态解析生成',seed:20250814,referenceDate:DEFAULT_REFERENCE_DATE,mode:'random',version:'1.0',tables}}
}

export async function importSchemaText(raw:string):Promise<ImportPreview> {
  if(new Blob([raw]).size>MAX_CONFIG_BYTES)throw new Error('Schema 文件不能超过 1 MB')
  if(/\bCREATE\s+TABLE\b/i.test(raw))return fromSql(raw)
  if(/\binterface\s+[A-Za-z_$][\w$]*(?:\s+extends\s+[^\{]+)?\s*\{|\btype\s+[A-Za-z_$][\w$]*\s*=\s*\{/.test(raw))return fromTypeScript(raw)
  let value:unknown;try{value=JSON.parse(raw)}catch{try{const{parseDocument}=await import('yaml'),document=parseDocument(raw,{prettyErrors:true,strict:true,uniqueKeys:true});const problems=[...document.errors,...document.warnings];if(problems.length)throw new Error(problems[0].message);value=document.toJS({maxAliasCount:100})}catch(reason){throw new Error(`无法解析 JSON/YAML：${reason instanceof Error?reason.message:'格式错误'}`)}}
  if(value&&typeof value==='object'&&!Array.isArray(value)&&typeof (value as Record<string,unknown>).openapi==='string')return fromOpenApi(value as Record<string,unknown>)
  return fromJson(value)
}
