import type { FieldRule, ProjectSchema, TableSchema } from '../types'
import { ENUM_VALUES } from '../data/enumValues'
import { createZip, GENERATOR_VERSION, sha256Fallback } from './exporters'
import { sortTables } from './modeling'

type Dialect='mysql'|'postgres'|'sqlite'
type ContractFile={name:string;content:string}
const encoder=new TextEncoder()
const safeName=(value:string)=>value.replace(/[^A-Za-z0-9_\u4e00-\u9fa5-]/g,'_').slice(0,80)||'mock-schema'
const quote=(value:string,dialect:Dialect)=>dialect==='mysql'?`\`${value.replaceAll('`','``')}\``:`"${value.replaceAll('"','""')}"`
const enumValues=(field:FieldRule)=>field.values?.length?field.values:ENUM_VALUES[field.generator]
const normalizedEnum=(field:FieldRule)=>enumValues(field)?.map(value=>field.dataType==='number'&&Number.isFinite(Number(value))?Number(value):field.dataType==='boolean'&&['true','false'].includes(String(value))?String(value)==='true':value)
const required=(field:FieldRule)=>(field.missing??0)===0&&(field.nullable??0)===0&&!field.condition
const formatFor=(field:FieldRule)=>({email:'email',uuid:'uuid',url:'uri',date:'date',pastDate:'date',futureDate:'date',dateTime:'date-time',ipv4:'ipv4',ipv6:'ipv6'} as Record<string,string>)[field.generator]

export function fieldJsonSchema(field:FieldRule){
  const schema:Record<string,unknown>={title:field.label,type:field.dataType==='date'?'string':field.dataType}
  const format=formatFor(field);if(format)schema.format=format
  const values=normalizedEnum(field);if(values?.length)schema.enum=values
  if(field.min!==undefined)schema.minimum=field.min;if(field.max!==undefined)schema.maximum=field.max;if(field.length!==undefined)schema.maxLength=field.length
  if(field.nullable)schema.type=[schema.type,'null']
  if(field.ref)schema['x-foreign-key']={tableId:field.ref.tableId,field:field.ref.field,strategy:field.ref.strategy??'random',...(field.ref.strategy==='hotspot'?{hotspotPercent:field.ref.hotspotPercent??20}:{})}
  if(field.generator)schema['x-mock-generator']=field.generator
  if(field.formula)schema['x-mock-formula']=field.formula
  if(field.condition)schema['x-mock-condition']=field.condition
  return schema
}

const tableJsonSchema=(table:TableSchema)=>{const requiredFields=table.fields.filter(required).map(field=>field.name);return{title:table.label,type:'object',additionalProperties:false,properties:Object.fromEntries(table.fields.map(field=>[field.name,fieldJsonSchema(field)])),...(requiredFields.length?{required:requiredFields}:{}),...(table.countByReference?{'x-mock-cardinality':table.countByReference}:{})}}

export function toJSONSchema(project:ProjectSchema){return{$schema:'https://json-schema.org/draft/2020-12/schema',$id:`urn:mock-data:${project.id}`,title:project.name,description:project.description,type:'object',properties:Object.fromEntries(project.tables.map(table=>[table.name,{type:'array',items:{$ref:`#/$defs/${table.name}`}}])),$defs:Object.fromEntries(project.tables.map(table=>[table.name,tableJsonSchema(table)])),'x-mock-seed':project.seed,'x-mock-mode':project.mode,'x-schema-version':project.version}}

export function toOpenAPI(project:ProjectSchema){return{openapi:'3.1.0',info:{title:`${project.name} Mock Contract`,description:project.description,version:project.version},paths:{},components:{schemas:Object.fromEntries(project.tables.map(table=>[table.name,tableJsonSchema(table)]))},'x-mock-project':{templateId:project.templateId,seed:project.seed,mode:project.mode}}}

const integerLike=new Set(['autoId','sequence','integer','positiveInt','negativeInt','age','playerLevel','experience','gold','fileSize','timestamp','percentage'])
const sqlType=(field:FieldRule,dialect:Dialect)=>{if(dialect==='sqlite')return field.dataType==='number'?(integerLike.has(field.generator)?'INTEGER':'REAL'):field.dataType==='boolean'?'INTEGER':'TEXT';if(field.dataType==='number'){if(integerLike.has(field.generator))return'BIGINT';return dialect==='mysql'?`DECIMAL(20, ${field.precision??2})`:`NUMERIC(20, ${field.precision??2})`}if(field.dataType==='boolean')return dialect==='mysql'?'TINYINT(1)':'BOOLEAN';if(field.dataType==='date')return dialect==='mysql'?'DATETIME':'TIMESTAMPTZ';if(field.dataType==='object')return dialect==='mysql'?'JSON':'JSONB';if(field.length&&field.length<=4000)return`VARCHAR(${Math.max(1,field.length)})`;return'TEXT'}

export function toDDL(project:ProjectSchema,dialect:Dialect){
  const lines=[`-- ${project.name} · Schema ${project.version} · generated by Mock造数工具`,`-- Dialect: ${dialect}`]
  for(const table of sortTables(project.tables)){const columns=table.fields.map(field=>{const constraints=[required(field)?'NOT NULL':'',field.primaryKey?'PRIMARY KEY':'',field.unique&&!field.primaryKey?'UNIQUE':''].filter(Boolean).join(' ');return`  ${quote(field.name,dialect)} ${sqlType(field,dialect)}${constraints?` ${constraints}`:''}`}),foreignKeys=table.fields.filter(field=>field.ref).map(field=>{const target=project.tables.find(candidate=>candidate.id===field.ref!.tableId);return target?`  FOREIGN KEY (${quote(field.name,dialect)}) REFERENCES ${quote(target.name,dialect)} (${quote(field.ref!.field,dialect)})`:''}).filter(Boolean);lines.push(`CREATE TABLE IF NOT EXISTS ${quote(table.name,dialect)} (\n${[...columns,...foreignKeys].join(',\n')}\n);`)}return`${lines.join('\n\n')}\n`
}

const typeName=(value:string)=>value.split(/[^A-Za-z0-9]+/).filter(Boolean).map(part=>part[0].toUpperCase()+part.slice(1)).join('')||'MockRecord'
const tsType=(field:FieldRule)=>{const values=normalizedEnum(field);let base=values?.length&&values.length<=50?values.map(value=>JSON.stringify(value)).join(' | '):field.dataType==='number'?'number':field.dataType==='boolean'?'boolean':field.dataType==='object'?'Record<string, unknown>':'string';if(field.nullable||field.condition?.otherwise==='null')base+=` | null`;return base}
export function toTypeScript(project:ProjectSchema){return`${project.tables.map(table=>`/** ${table.label} · 默认 ${table.count} 条 */\nexport interface ${typeName(table.name)} {\n${table.fields.map(field=>`  /** ${field.label}${field.ref?` · FK → ${field.ref.tableId}.${field.ref.field}`:''} */\n  ${field.name}${(field.missing??0)>0||field.condition?.otherwise==='omit'?'?':''}: ${tsType(field)};`).join('\n')}\n}`).join('\n\n')}\n`}

export function relationMarkdown(project:ProjectSchema){const labels={random:'种子随机',roundRobin:'轮询均匀',hotspot:'热点 80/20',oneToOne:'严格一对一'},relations=project.tables.flatMap(table=>table.fields.filter(field=>field.ref).map(field=>{const target=project.tables.find(candidate=>candidate.id===field.ref!.tableId),strategy=field.ref!.strategy??'random',cardinality=table.countByReference?.fieldId===field.id?table.countByReference:null;return`- \`${table.name}.${field.name}\` → \`${target?.name??field.ref!.tableId}.${field.ref!.field}\`（${cardinality?`每个父记录 ${cardinality.min}–${cardinality.max} 条`:`${labels[strategy]}${strategy==='hotspot'?`，热点池 ${field.ref!.hotspotPercent??20}%`:''}`}）`}));return`# ${project.name} Schema 关系说明\n\n- Schema 版本：${project.version}\n- 随机种子：${project.seed}\n- 造数模式：${project.mode}\n- 数据表：${project.tables.length}\n- 字段：${project.tables.reduce((sum,table)=>sum+table.fields.length,0)}\n\n## 数据表\n\n${sortTables(project.tables).map((table,index)=>`${index+1}. **${table.label}**（\`${table.name}\`）：${table.fields.length} 字段，${table.countByReference?`按父记录生成 ${table.countByReference.min}–${table.countByReference.max} 条子数据`:`默认 ${table.count} 条`}`).join('\n')}\n\n## 外键关系\n\n${relations.length?relations.join('\n'):'- 当前项目没有外键关系。'}\n`}

export function schemaContractFiles(project:ProjectSchema):ContractFile[]{return[
  {name:'json-schema.json',content:JSON.stringify(toJSONSchema(project),null,2)},
  {name:'openapi.json',content:JSON.stringify(toOpenAPI(project),null,2)},
  {name:'types.ts',content:toTypeScript(project)},
  {name:'ddl/mysql.sql',content:toDDL(project,'mysql')},
  {name:'ddl/postgres.sql',content:toDDL(project,'postgres')},
  {name:'ddl/sqlite.sql',content:toDDL(project,'sqlite')},
  {name:'RELATIONS.md',content:relationMarkdown(project)},
]}

const digest=async(value:string)=>{const bytes=encoder.encode(value);if(globalThis.crypto?.subtle)return[...new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256',bytes))].map(byte=>byte.toString(16).padStart(2,'0')).join('');return sha256Fallback(bytes)}
export async function createSchemaContractPackage(project:ProjectSchema){const createdAt=new Date(),files=schemaContractFiles(project),manifest={manifestVersion:1,kind:'schema-contract',projectName:project.name,schemaVersion:project.version,generatorVersion:GENERATOR_VERSION,randomSeed:project.seed,packagedAt:createdAt.toISOString(),files:await Promise.all(files.map(async file=>({name:file.name,bytes:encoder.encode(file.content).length,sha256:await digest(file.content)})))},zip=createZip([...files,{name:'manifest.json',content:JSON.stringify(manifest,null,2)}],createdAt);return{blob:new Blob([zip],{type:'application/zip'}),filename:`${safeName(project.name)}_schema.zip`,manifest}}
export async function exportSchemaContract(project:ProjectSchema){const result=await createSchemaContractPackage(project),url=URL.createObjectURL(result.blob),anchor=document.createElement('a');anchor.href=url;anchor.download=result.filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return result}
