import { useEffect, useMemo, useRef, useState, type KeyboardEvent as ReactKeyboardEvent } from 'react'
import { Command, Keyboard, Search, X } from './Icons'

export interface PaletteCommand {id:string;label:string;hint:string;group:string;keywords?:string;shortcut?:string;disabled?:boolean;action:()=>void|Promise<void>}

export const searchCommands=(commands:PaletteCommand[],query:string)=>{const terms=query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);if(!terms.length)return commands;return commands.filter(command=>{const haystack=`${command.label} ${command.hint} ${command.group} ${command.keywords||''}`.toLocaleLowerCase();return terms.every(term=>haystack.includes(term))})}

export default function CommandPalette({open,onClose,commands}:{open:boolean;onClose:()=>void;commands:PaletteCommand[]}){
  const[query,setQuery]=useState(''),[active,setActive]=useState(0),input=useRef<HTMLInputElement>(null),closeButton=useRef<HTMLButtonElement>(null),items=useRef<Array<HTMLButtonElement|null>>([]),filtered=useMemo(()=>searchCommands(commands,query),[commands,query])
  useEffect(()=>{if(open){const previous=document.activeElement as HTMLElement|null;setQuery('');setActive(0);requestAnimationFrame(()=>input.current?.focus());return()=>previous?.focus()}},[open])
  useEffect(()=>{if(!filtered[active]||filtered[active].disabled)setActive(Math.max(0,filtered.findIndex(command=>!command.disabled)))},[active,filtered])
  if(!open)return null
  const run=(command:PaletteCommand)=>{if(command.disabled)return;onClose();void command.action()}
  const nextEnabled=(start:number,direction:1|-1)=>{if(!filtered.length)return 0;let index=start;for(let step=0;step<filtered.length;step++){index=(index+direction+filtered.length)%filtered.length;if(!filtered[index].disabled)return index}return start}
  const keyDown=(event:ReactKeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();onClose()}else if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();const next=nextEnabled(active,event.key==='ArrowDown'?1:-1);setActive(next);items.current[next]?.scrollIntoView({block:'nearest'})}else if(event.key==='Enter'&&filtered[active]){event.preventDefault();run(filtered[active])}else if(event.key==='Tab'){const candidates:Array<HTMLElement|null>=[input.current,...items.current.slice(0,filtered.length).map(item=>item&&!item.disabled?item:null),closeButton.current],focusable=candidates.filter((item):item is HTMLElement=>item!==null);if(focusable.length){event.preventDefault();const current=focusable.indexOf(document.activeElement as HTMLElement),next=(current+(event.shiftKey?-1:1)+focusable.length)%focusable.length;focusable[next]?.focus()}}}
  let previousGroup=''
  return <div className="modal-backdrop command-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="command-palette" role="dialog" aria-modal="true" aria-label="命令中心" onKeyDown={keyDown}><header><Search/><input ref={input} role="combobox" aria-expanded="true" aria-controls="command-results" aria-activedescendant={filtered[active]?.id?`command-${filtered[active].id}`:undefined} value={query} onChange={event=>{setQuery(event.target.value);setActive(0)}} placeholder="搜索功能、场景、模式或面板…"/><kbd>ESC</kbd><button ref={closeButton} className="icon-button" onClick={onClose} aria-label="关闭命令中心"><X/></button></header><div className="command-results" id="command-results" role="listbox">{filtered.length?filtered.map((command,index)=>{const showGroup=command.group!==previousGroup;previousGroup=command.group;return <div className="command-entry" key={command.id}>{showGroup&&<p>{command.group}</p>}<button ref={element=>{items.current[index]=element}} id={`command-${command.id}`} role="option" aria-selected={index===active} disabled={command.disabled} className={index===active?'active':''} onMouseEnter={()=>!command.disabled&&setActive(index)} onClick={()=>run(command)}><Command/><span><strong>{command.label}</strong><small>{command.hint}</small></span>{command.shortcut&&<kbd>{command.shortcut}</kbd>}</button></div>}):<div className="command-empty"><Search/><strong>没有匹配命令</strong><span>试试“电商”“质量”“边界”或“导出”</span></div>}</div><footer><span><Keyboard/>↑↓ 选择</span><span><kbd>Enter</kbd> 执行</span><span><kbd>Esc</kbd> 关闭</span><b>{filtered.length} 个可用命令</b></footer></section></div>
}
