import { useRef, useState } from 'react'
import Papa from 'papaparse'
import { Download, FileJson, Layers3, Upload, X } from './Icons'
import { useAppStore } from '../store'
import { exportData } from '../lib/exporters'

export function ExportDialog({open,onClose}:{open:boolean;onClose:()=>void}) {
  const s=useAppStore();const [format,setFormat]=useState('json');if(!open)return null
  const formats=[['json','JSON','完整多表结构'],['jsonl','JSON Lines','当前表逐行 JSON'],['csv','CSV','当前表，通用表格'],['tsv','TSV','当前表，制表符分隔'],['xlsx','Excel XLSX','多表工作簿'],['mysql','MySQL SQL','批量 INSERT 脚本'],['postgres','PostgreSQL SQL','批量 INSERT 脚本'],['sqlite','SQLite SQL','批量 INSERT 脚本'],['postman','Postman 数据','Collection Runner'],['fixture','TS Fixture','Playwright / Cypress'],['markdown','覆盖报告','Markdown 文档']]
  const run=async()=>{if(!s.result)return;await exportData(format,s.project,s.result.data,s.result.report,s.activeTableId);onClose()}
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal"><header><div><span>EXPORT CENTER</span><h2>导出数据</h2></div><button className="icon-button" onClick={onClose}><X/></button></header>{!s.result?<div className="modal-empty">请先生成数据，再选择导出格式。</div>:<><div className="format-grid">{formats.map(([id,name,hint])=><button key={id} className={format===id?'active':''} onClick={()=>setFormat(id)}><FileJson/><span><strong>{name}</strong><small>{hint}</small></span></button>)}</div><div className="export-summary"><span>{s.project.name}</span><code>{s.result.report.totalRows.toLocaleString()} rows</code><code>seed {s.project.seed}</code><code>schema {s.project.version}</code></div></>}<footer><button className="button ghost" onClick={onClose}>取消</button><button className="button primary" disabled={!s.result} onClick={run}><Download/>下载文件</button></footer></section></div>
}

export function PoolDialog({open,onClose}:{open:boolean;onClose:()=>void}) {
  const {pools,setPools}=useAppStore();const [name,setName]=useState('业务渠道');const [text,setText]=useState('APP\n小程序\n官网\n线下门店');const input=useRef<HTMLInputElement>(null);if(!open)return null
  const add=()=>{const values=[...new Set(text.split(/[\n,]/).map(x=>x.trim()).filter(Boolean))];if(!name||!values.length)return;setPools([...pools,{id:`pool_${Date.now()}`,name,values,createdAt:new Date().toISOString()}]);setName('');setText('');}
  const parseFile=(file:File)=>{const reader=new FileReader();reader.onload=()=>{const raw=String(reader.result||'');if(file.name.endsWith('.json')){try{const j=JSON.parse(raw);setText((Array.isArray(j)?j:[]).map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join('\n'))}catch{setText(raw)}}else if(file.name.endsWith('.csv')){const r=Papa.parse<string[]>(raw);setText(r.data.map(row=>row[0]).filter(Boolean).join('\n'))}else setText(raw)};reader.readAsText(file)}
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal pool-modal"><header><div><span>LOCAL DATA POOL</span><h2>自定义数据池</h2><p>内置数据无需导入；这里只保存你的业务枚举。</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="pool-form"><label>数据池名称<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：渠道编码"/></label><label>候选值<textarea rows={7} value={text} onChange={e=>setText(e.target.value)} placeholder="每行一个值，也支持逗号分隔"/></label><div className="pool-actions"><input ref={input} hidden type="file" accept=".txt,.csv,.json" onChange={e=>e.target.files?.[0]&&parseFile(e.target.files[0])}/><button className="button ghost" onClick={()=>input.current?.click()}><Upload/>读取 TXT / CSV / JSON</button><button className="button primary" onClick={add}><Layers3/>保存数据池</button></div></div>{pools.length>0&&<div className="saved-pools"><h3>已保存</h3>{pools.map(p=><article key={p.id}><div><strong>{p.name}</strong><span>{p.values.length} 个值 · {p.values.slice(0,3).join('、')}</span></div><button className="icon-button danger" onClick={()=>setPools(pools.filter(x=>x.id!==p.id))}><X/></button></article>)}</div>}</section></div>
}
