import { useRef, useState } from 'react'
import Papa from 'papaparse'
import { Download, FileJson, HardDriveDownload, Layers3, RefreshCcw, RotateCcw, Trash2, Upload, X } from './Icons'
import { useAppStore } from '../store'
import { exportData } from '../lib/exporters'
import { cloneTemplate } from '../data/templates'
import { MAX_CONFIG_BYTES, parseProjectFile, safeProjectFilename, serializeProject } from '../lib/projectConfig'

export function ExportDialog({open,onClose}:{open:boolean;onClose:()=>void}) {
  const s=useAppStore();const [format,setFormat]=useState('json');if(!open)return null
  const formats=[['json','JSON','完整多表结构'],['jsonl','JSON Lines','当前表逐行 JSON'],['csv','CSV','当前表，通用表格'],['tsv','TSV','当前表，制表符分隔'],['xlsx','Excel XLSX','多表工作簿'],['mysql','MySQL SQL','批量 INSERT 脚本'],['postgres','PostgreSQL SQL','批量 INSERT 脚本'],['sqlite','SQLite SQL','批量 INSERT 脚本'],['postman','Postman 数据','Collection Runner'],['fixture','TS Fixture','Playwright / Cypress'],['markdown','覆盖报告','Markdown 文档']]
  const run=async()=>{if(!s.result)return;await exportData(format,s.project,s.result.data,s.result.report,s.activeTableId);onClose()}
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal"><header><div><span>EXPORT CENTER</span><h2>导出数据</h2></div><button className="icon-button" onClick={onClose}><X/></button></header>{!s.result?<div className="modal-empty">请先生成数据，再选择导出格式。</div>:<><div className="format-grid">{formats.map(([id,name,hint])=><button key={id} className={format===id?'active':''} onClick={()=>setFormat(id)}><FileJson/><span><strong>{name}</strong><small>{hint}</small></span></button>)}</div><div className="export-summary"><span>{s.project.name}</span><code>{s.result.report.totalRows.toLocaleString()} rows</code><code>seed {s.project.seed}</code><code>schema {s.project.version}</code></div></>}<footer><button className="button ghost" onClick={onClose}>取消</button><button className="button primary" disabled={!s.result} onClick={run}><Download/>下载文件</button></footer></section></div>
}

export function PoolDialog({open,onClose}:{open:boolean;onClose:()=>void}) {
  const {pools,setPools}=useAppStore();const [name,setName]=useState('业务渠道');const [text,setText]=useState('APP\n小程序\n官网\n线下门店');const [error,setError]=useState('');const input=useRef<HTMLInputElement>(null);if(!open)return null
  const add=()=>{const values=[...new Set(text.split(/[\n,]/).map(x=>x.trim()).filter(Boolean))];if(!name.trim())return setError('请输入数据池名称');if(!values.length)return setError('请至少输入一个候选值');if(values.length>10_000)return setError('单个数据池最多保存 10,000 个候选值');if(pools.some(pool=>pool.name===name.trim()))return setError('数据池名称不能重复');setPools([...pools,{id:`pool_${Date.now()}`,name:name.trim().slice(0,80),values:values.map(value=>value.slice(0,2_000)),createdAt:new Date().toISOString()}]);setName('');setText('');setError('')}
  const parseFile=(file:File)=>{setError('');if(file.size>MAX_CONFIG_BYTES)return setError('导入文件不能超过 1 MB');const reader=new FileReader();reader.onload=()=>{const raw=String(reader.result||'');if(file.name.toLowerCase().endsWith('.json')){try{const j=JSON.parse(raw);if(!Array.isArray(j))throw new Error();setText(j.slice(0,10_000).map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join('\n'))}catch{setError('JSON 数据池必须是数组')}}else if(file.name.toLowerCase().endsWith('.csv')){const r=Papa.parse<string[]>(raw,{skipEmptyLines:true});setText(r.data.slice(0,10_000).map(row=>row[0]).filter(Boolean).join('\n'))}else setText(raw.slice(0,MAX_CONFIG_BYTES))};reader.readAsText(file)}
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal pool-modal"><header><div><span>LOCAL DATA POOL</span><h2>自定义数据池</h2><p>内置数据无需导入；这里只保存你的业务枚举。</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="pool-form"><label>数据池名称<input value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder="例如：渠道编码"/></label><label>候选值<textarea rows={7} maxLength={MAX_CONFIG_BYTES} value={text} onChange={e=>setText(e.target.value)} placeholder="每行一个值，也支持逗号分隔"/></label>{error&&<div className="form-error">{error}</div>}<div className="pool-actions"><input ref={input} hidden type="file" accept=".txt,.csv,.json" onChange={e=>e.target.files?.[0]&&parseFile(e.target.files[0])}/><button className="button ghost" onClick={()=>input.current?.click()}><Upload/>读取 TXT / CSV / JSON</button><button className="button primary" onClick={add}><Layers3/>保存数据池</button></div></div>{pools.length>0&&<div className="saved-pools"><h3>已保存</h3>{pools.map(p=><article key={p.id}><div><strong>{p.name}</strong><span>{p.values.length} 个值 · {p.values.slice(0,3).join('、')}</span></div><button className="icon-button danger" onClick={()=>setPools(pools.filter(x=>x.id!==p.id))}><X/></button></article>)}</div>}</section></div>
}

const downloadText=(text:string,name:string)=>{const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function ProjectDialog({open,onClose}:{open:boolean;onClose:()=>void}) {
  const {project,pools,setProject,setPools}=useAppStore();const input=useRef<HTMLInputElement>(null);const [error,setError]=useState('');const [message,setMessage]=useState('');if(!open)return null
  const exportProject=()=>{downloadText(serializeProject(project),safeProjectFilename(project.name));setMessage('项目配置已下载，不包含生成结果和数据池内容。');setError('')}
  const importProject=(file:File)=>{setError('');setMessage('');if(file.size>MAX_CONFIG_BYTES)return setError('配置文件不能超过 1 MB');const reader=new FileReader();reader.onload=()=>{try{setProject(parseProjectFile(String(reader.result||'')));setMessage('项目配置已恢复，请重新生成数据。')}catch(reason){setError(reason instanceof Error?reason.message:'导入失败')}};reader.readAsText(file)}
  const restore=()=>{setProject(cloneTemplate(project.templateId));setMessage('已恢复当前场景的内置模板。');setError('')}
  const clear=()=>{if(!window.confirm('确定清除当前项目、自定义数据池和浏览器本地配置吗？此操作无法撤销。'))return;localStorage.removeItem('mock-tool-ui');setPools([]);setProject(cloneTemplate('commerce'));setMessage('本地数据已清除，已恢复默认电商模板。');setError('')}
  return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="modal project-modal"><header><div><span>PROJECT SAFETY</span><h2>项目与本地数据</h2><p>备份规则、恢复模板或清理当前浏览器中的数据。</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="project-actions"><article><HardDriveDownload/><div><strong>备份项目配置</strong><p>下载经过版本标记的 `.mock.json`，不包含已生成的数据。</p></div><button className="button ghost" onClick={exportProject}>下载配置</button></article><article><Upload/><div><strong>恢复项目配置</strong><p>仅接受本工具生成且通过安全校验的配置，最大 1 MB。</p></div><input hidden ref={input} type="file" accept=".mock.json,application/json" onChange={event=>event.target.files?.[0]&&importProject(event.target.files[0])}/><button className="button ghost" onClick={()=>input.current?.click()}>选择文件</button></article><article><RotateCcw/><div><strong>恢复内置模板</strong><p>放弃当前修改，重新加载“{project.templateId}”场景模板。</p></div><button className="button ghost" onClick={restore}>恢复模板</button></article><article className="danger-zone"><Trash2/><div><strong>清除本地数据</strong><p>删除当前项目与 {pools.length} 个自定义数据池，不影响网站本身。</p></div><button className="button danger-button" onClick={clear}>清除数据</button></article></div>{error&&<div className="dialog-message error">{error}</div>}{message&&<div className="dialog-message success">{message}</div>}<footer><span className="privacy-note">所有操作仅发生在当前浏览器中</span><button className="button primary" onClick={onClose}>完成</button></footer></section></div>
}
