import { Copy, Trash2, ArrowDown, ArrowUp, Plus, WandSparkles } from './Icons'
import { ENUM_SIZES, GENERATORS } from '../data/generatorCatalog'
import { useAppStore } from '../store'
import type { ConditionOperator, DataType, FieldCondition, ReferenceStrategy, RelationValueRule } from '../types'

const OPERATORS: Array<[ConditionOperator, string]> = [['equals','等于'],['notEquals','不等于'],['contains','包含'],['greaterThan','大于'],['lessThan','小于'],['empty','为空'],['notEmpty','不为空']]

export default function FieldEditor() {
  const s=useAppStore();const table=s.project.tables.find(t=>t.id===s.activeTableId);const field=table?.fields.find(f=>f.id===s.selectedFieldId)
  if(!table||!field)return <main className="editor empty-state"><WandSparkles/><h2>选择一个字段</h2><p>从左侧选择字段，配置它的生成规则。</p></main>
  const update=(patch:Record<string,unknown>)=>s.updateField(table.id,field.id,patch)
  const categories=[...new Set(GENERATORS.map(g=>g.category))]
  return <main className="editor">
    <header className="editor-head"><div><span className={`type-badge ${field.dataType}`}>{field.dataType}</span><div><h2>{field.label}</h2><p>{table.label} / <code>{field.name}</code></p></div></div><div><button className="icon-button" onClick={()=>s.moveField(field.id,-1)} title="上移"><ArrowUp size={16}/></button><button className="icon-button" onClick={()=>s.moveField(field.id,1)} title="下移"><ArrowDown size={16}/></button><button className="icon-button" onClick={()=>s.duplicateField(field.id)} title="复制"><Copy size={16}/></button><button className="icon-button danger" onClick={()=>s.removeField(field.id)} title="删除"><Trash2 size={16}/></button></div></header>
    <section className="form-card"><div className="card-kicker">字段定义</div><div className="form-grid two"><label>显示名称<input value={field.label} onChange={e=>update({label:e.target.value})}/></label><label>字段名<input className="mono" value={field.name} onChange={e=>update({name:e.target.value.replace(/\s/g,'_')})}/></label></div><div className="form-grid two"><label>数据类型<select value={field.dataType} onChange={e=>update({dataType:e.target.value as DataType})}><option value="string">字符串 string</option><option value="number">数字 number</option><option value="boolean">布尔 boolean</option><option value="date">日期 date</option><option value="object">对象 object</option></select></label><label>生成器<select value={field.generator} onChange={e=>{const g=GENERATORS.find(x=>x.key===e.target.value);update({generator:e.target.value,dataType:g?.dataType||field.dataType})}}>{categories.map(c=><optgroup key={c} label={c}>{GENERATORS.filter(g=>g.category===c).map(g=><option key={g.key} value={g.key}>{g.name}</option>)}</optgroup>)}</select></label></div></section>
    <section className="form-card"><div className="card-kicker">生成规则</div><div className="form-grid three"><label>最小值<input type="number" value={field.min??''} placeholder="自动" onChange={e=>update({min:e.target.value===''?undefined:Number(e.target.value)})}/></label><label>最大值<input type="number" value={field.max??''} placeholder="自动" onChange={e=>update({max:e.target.value===''?undefined:Number(e.target.value)})}/></label><label>精度<input type="number" min="0" max="8" value={field.precision??''} placeholder="自动" onChange={e=>update({precision:e.target.value===''?undefined:Number(e.target.value)})}/></label></div><div className="form-grid two"><label>前缀<input value={field.prefix??''} placeholder="例如 TEST-" onChange={e=>update({prefix:e.target.value})}/></label><label>后缀<input value={field.suffix??''} placeholder="例如 -CN" onChange={e=>update({suffix:e.target.value})}/></label></div>{['customEnum'].includes(field.generator)&&<label>枚举值（逗号分隔）<textarea rows={2} value={field.values?.join(',')??''} onChange={e=>update({values:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label>}{['fixed','dataPool'].includes(field.generator)&&<label>{field.generator==='dataPool'?'数据池名称':'固定值'}<input value={field.fixedValue??''} placeholder={field.generator==='dataPool'?'选择已创建的数据池名称':'输入固定内容'} onChange={e=>update({fixedValue:e.target.value})}/></label>}{field.generator==='template'&&<label>格式模板<input className="mono" value={field.format??'{date}-{seq}'} onChange={e=>update({format:e.target.value})}/><small>可使用 {'{date}'}、{'{seq}'}</small></label>}<label>安全计算公式（可选）<input className="mono" disabled={!!field.relationValue} value={field.formula??''} placeholder="round(price * quantity - discount, 2)" onChange={e=>update({formula:e.target.value})}/><small>{field.relationValue?'已由跨表规则接管此字段':'支持四则运算、条件、concat、round、min/max、length、coalesce、dateAdd/dateDiff；不执行 JavaScript'}</small></label></section>
    <section className="form-card"><div className="card-kicker">跨表计算</div><RelationValueEditor project={s.project} tableId={table.id} value={field.relationValue} onChange={relationValue=>update({relationValue,formula:relationValue?undefined:field.formula})}/></section>
    {s.project.mode==='realistic'&&<section className="form-card distribution-card"><div className="card-kicker">真实分布</div><div className="distribution-intro"><span>此配置仅在“真实分布”模式生效</span><small>相同种子与规则始终产生相同结果</small></div><label>分布类型<select value={field.distribution??'uniform'} onChange={event=>update({distribution:event.target.value})}><option value="uniform">均匀分布</option><option value="normal">正态分布</option><option value="longTail">长尾分布（少量大值）</option><option value="hotspot">热点分布（80% 靠近中心）</option><option value="ascending">递增趋势</option><option value="descending">递减趋势</option></select></label>{field.dataType==='number'&&['normal','hotspot'].includes(field.distribution??'')&&<label>分布中心（实际数值）<input type="number" value={field.distributionCenter??''} placeholder="默认位于范围中部" onChange={event=>update({distributionCenter:event.target.value===''?undefined:Number(event.target.value)})}/></label>}{(field.values?.length||field.generator==='dataPool'||ENUM_SIZES[field.generator])&&<label>候选项权重（逗号分隔）<input className="mono" value={field.weights?.join(',')??''} placeholder={Array.from({length:field.values?.length||ENUM_SIZES[field.generator]||4},(_,index)=>index===0?'70':'10').join(',')} onChange={event=>update({weights:event.target.value.split(/[,，]/).map(value=>Number(value.trim())).filter(value=>Number.isFinite(value)&&value>=0)})}/><small>按候选值顺序填写非负数，系统自动归一化，无需合计 100</small></label>}<DistributionPreview field={field}/></section>}
    <section className="form-card"><div className="card-kicker">条件生成</div><ConditionEditor condition={field.condition} fields={table.fields.filter(candidate=>candidate.id!==field.id).map(candidate=>({name:candidate.name,label:candidate.label}))} onChange={condition=>update({condition})}/></section>
    <section className="form-card"><div className="card-kicker">约束与异常</div><div className="switch-grid"><label><input type="checkbox" checked={!!field.unique} onChange={e=>update({unique:e.target.checked})}/><span>唯一值</span></label><label><input type="checkbox" checked={!!field.primaryKey} onChange={e=>update({primaryKey:e.target.checked,unique:e.target.checked||field.unique})}/><span>主键</span></label></div><div className="form-grid three"><label>空值率 <b>{field.nullable??0}%</b><input type="range" min="0" max="100" value={field.nullable??0} onChange={e=>update({nullable:Number(e.target.value)})}/></label><label>缺失率 <b>{field.missing??0}%</b><input type="range" min="0" max="100" value={field.missing??0} onChange={e=>update({missing:Number(e.target.value)})}/></label><label>异常率 <b>{field.abnormal??0}%</b><input className="orange" type="range" min="0" max="100" value={field.abnormal??0} onChange={e=>update({abnormal:Number(e.target.value)})}/></label></div><div className="form-grid two"><label>引用其他表<select value={field.ref?`${field.ref.tableId}.${field.ref.field}`:''} onChange={e=>{if(!e.target.value)return update({ref:undefined});const [tableId,...rest]=e.target.value.split('.');update({ref:{tableId,field:rest.join('.'),strategy:field.ref?.strategy??'random'}})}}><option value="">不引用</option>{s.project.tables.filter(t=>t.id!==table.id).flatMap(t=>t.fields.filter(f=>f.primaryKey||f.unique).map(f=><option key={`${t.id}.${f.name}`} value={`${t.id}.${f.name}`}>{t.label}.{f.label}</option>))}</select></label>{field.ref&&<label>引用分配策略<select value={field.ref.strategy??'random'} onChange={e=>{const strategy=e.target.value as ReferenceStrategy;update({ref:{...field.ref!,strategy},...(strategy==='oneToOne'?{nullable:0,missing:0}:{})})}}><option value="random">种子随机 · 自然分散</option><option value="roundRobin">轮询均匀 · 压测分片</option><option value="hotspot">热点 80/20 · 流量倾斜</option><option value="oneToOne">严格一对一 · 唯一绑定</option></select></label>}</div>{field.ref&&<div className="reference-strategy-note"><strong>{field.ref.strategy==='roundRobin'?'每个父记录被依次引用，使用次数最多相差 1 次。':field.ref.strategy==='hotspot'?'80% 的引用集中到前部热点池，适合缓存和热点账户测试。':field.ref.strategy==='oneToOne'?'每个父记录最多使用一次；父表数量不足时阻止生成。':'使用固定种子的随机分配；相同配置始终可复现。'}</strong>{field.ref.strategy==='hotspot'&&<label>热点池占父表 <b>{field.ref.hotspotPercent??20}%</b><input type="range" min="1" max="50" value={field.ref.hotspotPercent??20} onChange={e=>update({ref:{...field.ref!,hotspotPercent:Number(e.target.value)}})}/></label>}</div>}</section>
  </main>
}

function RelationValueEditor({project,tableId,value,onChange}:{project:import('../types').ProjectSchema;tableId:string;value?:RelationValueRule;onChange:(value:RelationValueRule|undefined)=>void}){
  const table=project.tables.find(candidate=>candidate.id===tableId)!,primary=table.fields.find(field=>field.primaryKey)??table.fields.find(field=>field.unique),children=project.tables.flatMap(source=>source.fields.filter(field=>field.ref?.tableId===tableId&&(!primary||field.ref.field===primary.name)).map(field=>({source,field}))),foreignKeys=table.fields.filter(field=>field.ref),lookupField=value?.kind==='lookup'?foreignKeys.find(field=>field.name===value.localForeignKey)??foreignKeys[0]:foreignKeys[0],lookupSource=lookupField?.ref?project.tables.find(candidate=>candidate.id===lookupField.ref!.tableId):undefined
  const enableAggregate=()=>{const child=children[0];if(child)onChange({kind:'aggregate',sourceTableId:child.source.id,sourceForeignKey:child.field.name,expression:child.source.fields.find(field=>field.dataType==='number'&&!field.ref)?.name||'1',operation:'sum',precision:2})}
  const enableLookup=()=>{if(lookupField?.ref&&lookupSource)onChange({kind:'lookup',localForeignKey:lookupField.name,sourceTableId:lookupSource.id,sourceKey:lookupField.ref.field,sourceField:lookupSource.fields.find(field=>!field.primaryKey)?.name||lookupField.ref.field})}
  if(!value)return <div className="relation-value-empty"><div><strong>让字段与关联表保持业务一致</strong><span>例如订单金额汇总明细，支付金额回填订单金额。规则只做白名单计算。</span></div><button className="button ghost" disabled={!children.length} onClick={enableAggregate}>汇总子表</button><button className="button ghost" disabled={!foreignKeys.length} onClick={enableLookup}>从父表回填</button></div>
  if(value.kind==='aggregate'){const candidates=children,selected=candidates.find(item=>item.source.id===value.sourceTableId&&item.field.name===value.sourceForeignKey)??candidates[0],source=selected?.source;const updateRule=(patch:Partial<Extract<RelationValueRule,{kind:'aggregate'}>>)=>onChange({...value,...patch});return <div className="relation-value-editor"><header><strong>汇总子表记录</strong><button onClick={()=>onChange(undefined)}>关闭规则</button></header><div className="form-grid two"><label>明细关联<select value={`${value.sourceTableId}.${value.sourceForeignKey}`} onChange={event=>{const [sourceTableId,...rest]=event.target.value.split('.');updateRule({sourceTableId,sourceForeignKey:rest.join('.')})}}>{candidates.map(item=><option key={`${item.source.id}.${item.field.name}`} value={`${item.source.id}.${item.field.name}`}>{item.source.label}.{item.field.label}</option>)}</select></label><label>聚合方式<select value={value.operation} onChange={event=>updateRule({operation:event.target.value as 'sum'|'count'|'min'|'max'})}><option value="sum">求和 SUM</option><option value="count">计数 COUNT</option><option value="min">最小值 MIN</option><option value="max">最大值 MAX</option></select></label></div>{value.operation!=='count'&&<div className="form-grid two"><label>明细表达式<input className="mono" value={value.expression} onChange={event=>updateRule({expression:event.target.value})}/><small>可用字段：{source?.fields.map(field=>field.name).join('、')}</small></label><label>小数精度<input type="number" min="0" max="12" value={value.precision??2} onChange={event=>updateRule({precision:Number(event.target.value)})}/></label></div>}</div>}
  const updateRule=(patch:Partial<Extract<RelationValueRule,{kind:'lookup'}>>)=>onChange({...value,...patch});return <div className="relation-value-editor"><header><strong>从父表回填字段</strong><button onClick={()=>onChange(undefined)}>关闭规则</button></header><div className="form-grid two"><label>当前表外键<select value={value.localForeignKey} onChange={event=>{const field=foreignKeys.find(candidate=>candidate.name===event.target.value)!,source=project.tables.find(candidate=>candidate.id===field.ref!.tableId)!;updateRule({localForeignKey:field.name,sourceTableId:source.id,sourceKey:field.ref!.field,sourceField:source.fields.find(candidate=>!candidate.primaryKey)?.name||field.ref!.field})}}>{foreignKeys.map(field=><option key={field.id} value={field.name}>{field.label} · {field.name}</option>)}</select></label><label>回填字段<select value={value.sourceField} onChange={event=>updateRule({sourceField:event.target.value})}>{lookupSource?.fields.map(field=><option key={field.id} value={field.name}>{lookupSource.label}.{field.label}</option>)}</select></label></div></div>
}

function DistributionPreview({field}:{field:import('../types').FieldRule}){const type=field.distribution||'uniform',shapes={uniform:[5,5,5,5,5,5,5,5],normal:[1,2,5,8,8,5,2,1],longTail:[8,6,4,3,2,1,.7,.4],hotspot:[1,1,2,8,8,2,1,1],ascending:[1,2,3,4,5,6,7,8],descending:[8,7,6,5,4,3,2,1]},weights=field.weights?.length?field.weights:shapes[type],max=Math.max(...weights,1);return <div className="distribution-preview"><div>{type==='normal'?'正态':type==='longTail'?'长尾':type==='hotspot'?'热点':type==='ascending'?'递增':type==='descending'?'递减':'均匀'}预览</div><span>{weights.slice(0,8).map((weight,index)=><i key={index} style={{height:`${Math.max(8,weight/max*42)}px`}}></i>)}</span></div>}

function ConditionEditor({condition,fields,onChange}:{condition?:FieldCondition;fields:Array<{name:string;label:string}>;onChange:(condition:FieldCondition|undefined)=>void}) {
  const enable=()=>onChange({combinator:'and',rules:[{field:fields[0]?.name||'',operator:'equals',value:''}],otherwise:'null'})
  if(!condition)return <div className="condition-empty"><div><strong>仅在满足业务条件时保留此字段</strong><span>例如“支付状态等于成功时，才生成支付时间”。规则不会执行任意脚本。</span></div><button className="button ghost" disabled={!fields.length} onClick={enable}><Plus/>添加条件</button></div>
  const updateRule=(index:number,patch:Partial<FieldCondition['rules'][number]>)=>onChange({...condition,rules:condition.rules.map((rule,i)=>i===index?{...rule,...patch}:rule)})
  return <div className="condition-builder"><div className="condition-summary"><span>满足</span><select aria-label="条件组合方式" value={condition.combinator} onChange={event=>onChange({...condition,combinator:event.target.value as 'and'|'or'})}><option value="and">全部条件 AND</option><option value="or">任一条件 OR</option></select><span>时生成</span><button onClick={()=>onChange(undefined)}>关闭条件</button></div><div className="condition-rules">{condition.rules.map((rule,index)=><div className="condition-rule" key={index}><i>{index+1}</i><select aria-label={`条件 ${index+1} 来源字段`} value={rule.field} onChange={event=>updateRule(index,{field:event.target.value})}>{fields.map(candidate=><option key={candidate.name} value={candidate.name}>{candidate.label} · {candidate.name}</option>)}</select><select aria-label={`条件 ${index+1} 运算符`} value={rule.operator} onChange={event=>updateRule(index,{operator:event.target.value as ConditionOperator})}>{OPERATORS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{!['empty','notEmpty'].includes(rule.operator)?<input aria-label={`条件 ${index+1} 比较值`} value={rule.value??''} onChange={event=>updateRule(index,{value:event.target.value})} placeholder="比较值"/>:<span className="condition-no-value">无需比较值</span>}<button className="icon-button danger" disabled={condition.rules.length===1} onClick={()=>onChange({...condition,rules:condition.rules.filter((_,i)=>i!==index)})}><Trash2/></button></div>)}</div><footer><button className="condition-add" disabled={condition.rules.length>=10} onClick={()=>onChange({...condition,rules:[...condition.rules,{field:fields[0]?.name||'',operator:'equals',value:''}]})}><Plus/>添加一条条件</button><label>不满足时<select value={condition.otherwise} onChange={event=>onChange({...condition,otherwise:event.target.value as 'null'|'omit'})}><option value="null">设为 NULL</option><option value="omit">移除字段</option></select></label></footer></div>
}
