import { Copy, Trash2, ArrowDown, ArrowUp, Plus, WandSparkles } from './Icons'
import { GENERATORS } from '../data/generators'
import { useAppStore } from '../store'
import type { ConditionOperator, DataType, FieldCondition } from '../types'

const OPERATORS: Array<[ConditionOperator, string]> = [['equals','等于'],['notEquals','不等于'],['contains','包含'],['greaterThan','大于'],['lessThan','小于'],['empty','为空'],['notEmpty','不为空']]

export default function FieldEditor() {
  const s=useAppStore();const table=s.project.tables.find(t=>t.id===s.activeTableId);const field=table?.fields.find(f=>f.id===s.selectedFieldId)
  if(!table||!field)return <main className="editor empty-state"><WandSparkles/><h2>选择一个字段</h2><p>从左侧选择字段，配置它的生成规则。</p></main>
  const update=(patch:Record<string,unknown>)=>s.updateField(table.id,field.id,patch)
  const categories=[...new Set(GENERATORS.map(g=>g.category))]
  return <main className="editor">
    <header className="editor-head"><div><span className={`type-badge ${field.dataType}`}>{field.dataType}</span><div><h2>{field.label}</h2><p>{table.label} / <code>{field.name}</code></p></div></div><div><button className="icon-button" onClick={()=>s.moveField(field.id,-1)} title="上移"><ArrowUp size={16}/></button><button className="icon-button" onClick={()=>s.moveField(field.id,1)} title="下移"><ArrowDown size={16}/></button><button className="icon-button" onClick={()=>s.duplicateField(field.id)} title="复制"><Copy size={16}/></button><button className="icon-button danger" onClick={()=>s.removeField(field.id)} title="删除"><Trash2 size={16}/></button></div></header>
    <section className="form-card"><div className="card-kicker">字段定义</div><div className="form-grid two"><label>显示名称<input value={field.label} onChange={e=>update({label:e.target.value})}/></label><label>字段名<input className="mono" value={field.name} onChange={e=>update({name:e.target.value.replace(/\s/g,'_')})}/></label></div><div className="form-grid two"><label>数据类型<select value={field.dataType} onChange={e=>update({dataType:e.target.value as DataType})}><option value="string">字符串 string</option><option value="number">数字 number</option><option value="boolean">布尔 boolean</option><option value="date">日期 date</option><option value="object">对象 object</option></select></label><label>生成器<select value={field.generator} onChange={e=>{const g=GENERATORS.find(x=>x.key===e.target.value);update({generator:e.target.value,dataType:g?.dataType||field.dataType})}}>{categories.map(c=><optgroup key={c} label={c}>{GENERATORS.filter(g=>g.category===c).map(g=><option key={g.key} value={g.key}>{g.name}</option>)}</optgroup>)}</select></label></div></section>
    <section className="form-card"><div className="card-kicker">生成规则</div><div className="form-grid three"><label>最小值<input type="number" value={field.min??''} placeholder="自动" onChange={e=>update({min:e.target.value===''?undefined:Number(e.target.value)})}/></label><label>最大值<input type="number" value={field.max??''} placeholder="自动" onChange={e=>update({max:e.target.value===''?undefined:Number(e.target.value)})}/></label><label>精度<input type="number" min="0" max="8" value={field.precision??''} placeholder="自动" onChange={e=>update({precision:e.target.value===''?undefined:Number(e.target.value)})}/></label></div><div className="form-grid two"><label>前缀<input value={field.prefix??''} placeholder="例如 TEST-" onChange={e=>update({prefix:e.target.value})}/></label><label>后缀<input value={field.suffix??''} placeholder="例如 -CN" onChange={e=>update({suffix:e.target.value})}/></label></div>{['customEnum'].includes(field.generator)&&<label>枚举值（逗号分隔）<textarea rows={2} value={field.values?.join(',')??''} onChange={e=>update({values:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})}/></label>}{['fixed','dataPool'].includes(field.generator)&&<label>{field.generator==='dataPool'?'数据池名称':'固定值'}<input value={field.fixedValue??''} placeholder={field.generator==='dataPool'?'选择已创建的数据池名称':'输入固定内容'} onChange={e=>update({fixedValue:e.target.value})}/></label>}{field.generator==='template'&&<label>格式模板<input className="mono" value={field.format??'{date}-{seq}'} onChange={e=>update({format:e.target.value})}/><small>可使用 {'{date}'}、{'{seq}'}</small></label>}<label>安全计算公式（可选）<input className="mono" value={field.formula??''} placeholder="round(price * quantity - discount, 2)" onChange={e=>update({formula:e.target.value})}/><small>支持乘法取整、字段拼接和字段引用，不执行 JavaScript</small></label></section>
    <section className="form-card"><div className="card-kicker">条件生成</div><ConditionEditor condition={field.condition} fields={table.fields.filter(candidate=>candidate.id!==field.id).map(candidate=>({name:candidate.name,label:candidate.label}))} onChange={condition=>update({condition})}/></section>
    <section className="form-card"><div className="card-kicker">约束与异常</div><div className="switch-grid"><label><input type="checkbox" checked={!!field.unique} onChange={e=>update({unique:e.target.checked})}/><span>唯一值</span></label><label><input type="checkbox" checked={!!field.primaryKey} onChange={e=>update({primaryKey:e.target.checked,unique:e.target.checked||field.unique})}/><span>主键</span></label></div><div className="form-grid three"><label>空值率 <b>{field.nullable??0}%</b><input type="range" min="0" max="100" value={field.nullable??0} onChange={e=>update({nullable:Number(e.target.value)})}/></label><label>缺失率 <b>{field.missing??0}%</b><input type="range" min="0" max="100" value={field.missing??0} onChange={e=>update({missing:Number(e.target.value)})}/></label><label>异常率 <b>{field.abnormal??0}%</b><input className="orange" type="range" min="0" max="100" value={field.abnormal??0} onChange={e=>update({abnormal:Number(e.target.value)})}/></label></div><label>引用其他表<select value={field.ref?`${field.ref.tableId}.${field.ref.field}`:''} onChange={e=>{if(!e.target.value)return update({ref:undefined});const [tableId,...rest]=e.target.value.split('.');update({ref:{tableId,field:rest.join('.')}})}}><option value="">不引用</option>{s.project.tables.filter(t=>t.id!==table.id).flatMap(t=>t.fields.filter(f=>f.primaryKey||f.unique).map(f=><option key={`${t.id}.${f.name}`} value={`${t.id}.${f.name}`}>{t.label}.{f.label}</option>))}</select></label></section>
  </main>
}

function ConditionEditor({condition,fields,onChange}:{condition?:FieldCondition;fields:Array<{name:string;label:string}>;onChange:(condition:FieldCondition|undefined)=>void}) {
  const enable=()=>onChange({combinator:'and',rules:[{field:fields[0]?.name||'',operator:'equals',value:''}],otherwise:'null'})
  if(!condition)return <div className="condition-empty"><div><strong>仅在满足业务条件时保留此字段</strong><span>例如“支付状态等于成功时，才生成支付时间”。规则不会执行任意脚本。</span></div><button className="button ghost" disabled={!fields.length} onClick={enable}><Plus/>添加条件</button></div>
  const updateRule=(index:number,patch:Partial<FieldCondition['rules'][number]>)=>onChange({...condition,rules:condition.rules.map((rule,i)=>i===index?{...rule,...patch}:rule)})
  return <div className="condition-builder"><div className="condition-summary"><span>满足</span><select aria-label="条件组合方式" value={condition.combinator} onChange={event=>onChange({...condition,combinator:event.target.value as 'and'|'or'})}><option value="and">全部条件 AND</option><option value="or">任一条件 OR</option></select><span>时生成</span><button onClick={()=>onChange(undefined)}>关闭条件</button></div><div className="condition-rules">{condition.rules.map((rule,index)=><div className="condition-rule" key={index}><i>{index+1}</i><select aria-label={`条件 ${index+1} 来源字段`} value={rule.field} onChange={event=>updateRule(index,{field:event.target.value})}>{fields.map(candidate=><option key={candidate.name} value={candidate.name}>{candidate.label} · {candidate.name}</option>)}</select><select aria-label={`条件 ${index+1} 运算符`} value={rule.operator} onChange={event=>updateRule(index,{operator:event.target.value as ConditionOperator})}>{OPERATORS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{!['empty','notEmpty'].includes(rule.operator)?<input aria-label={`条件 ${index+1} 比较值`} value={rule.value??''} onChange={event=>updateRule(index,{value:event.target.value})} placeholder="比较值"/>:<span className="condition-no-value">无需比较值</span>}<button className="icon-button danger" disabled={condition.rules.length===1} onClick={()=>onChange({...condition,rules:condition.rules.filter((_,i)=>i!==index)})}><Trash2/></button></div>)}</div><footer><button className="condition-add" disabled={condition.rules.length>=10} onClick={()=>onChange({...condition,rules:[...condition.rules,{field:fields[0]?.name||'',operator:'equals',value:''}]})}><Plus/>添加一条条件</button><label>不满足时<select value={condition.otherwise} onChange={event=>onChange({...condition,otherwise:event.target.value as 'null'|'omit'})}><option value="null">设为 NULL</option><option value="omit">移除字段</option></select></label></footer></div>
}
