import { useMemo, useState } from 'react'
import { FIELD_PACKS, planFieldPack, type FieldConflictStrategy } from '../data/fieldPacks'
import { useAppStore } from '../store'
import { Check, PackagePlus, X } from './Icons'

export default function FieldPackDialog({open,onClose}:{open:boolean;onClose:()=>void}){
  const{project,activeTableId,appendFields}=useAppStore(),[packId,setPackId]=useState(FIELD_PACKS[0].id),[strategy,setStrategy]=useState<FieldConflictStrategy>('skip'),table=project.tables.find(candidate=>candidate.id===activeTableId),plan=useMemo(()=>table?planFieldPack(table.fields,packId,strategy):null,[packId,strategy,table]),tooMany=Boolean(table&&plan&&table.fields.length+plan.fields.length>200)
  if(!open||!table||!plan)return null
  const apply=()=>{if(!plan.fields.length||tooMany)return;appendFields(table.id,plan.fields);onClose()}
  return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="modal field-pack-modal" role="dialog" aria-modal="true" aria-label="添加字段套餐"><header><div><span>FIELD PACKS</span><h2>一组添加常用字段</h2><p>为“{table.label}”快速补齐业务与工程字段，整组操作只产生一次撤销记录。</p></div><button className="icon-button" onClick={onClose} aria-label="关闭字段套餐"><X/></button></header><div className="field-pack-layout"><div className="field-pack-list">{FIELD_PACKS.map(pack=><button key={pack.id} className={pack.id===packId?'active':''} onClick={()=>setPackId(pack.id)}><PackagePlus/><span><strong>{pack.name}</strong><small>{pack.description}</small></span><em>{pack.fields.length}</em></button>)}</div><div className="field-pack-preview"><header><div><span>{plan.pack.category}</span><strong>{plan.pack.name}</strong><small>{plan.pack.description}</small></div><b>+{plan.fields.length}</b></header>{plan.conflicts.length>0&&<div className="field-pack-conflict"><strong>发现 {plan.conflicts.length} 个同名字段</strong><span>{plan.conflicts.join('、')}</span><label>处理方式<select value={strategy} onChange={event=>setStrategy(event.target.value as FieldConflictStrategy)}><option value="skip">跳过已有字段（推荐）</option><option value="rename">自动添加 _2 后缀</option></select></label></div>}<div className="field-pack-fields">{plan.fields.map(field=><article key={field.id}><Check/><span><strong>{field.label}</strong><code>{field.name}</code></span><em>{field.dataType}</em></article>)}{!plan.fields.length&&<p>套餐中的字段都已存在，无需重复添加。</p>}</div>{plan.renamed.length>0&&<small className="rename-note">自动重命名：{plan.renamed.map(item=>`${item.from} → ${item.to}`).join('；')}</small>}{tooMany&&<div className="form-error">添加后将超过每表 200 字段上限，请先删除不需要的字段。</div>}</div></div><footer><span className="privacy-note">当前 {table.fields.length} 字段 · 添加后 {table.fields.length+plan.fields.length} 字段</span><button className="button ghost" onClick={onClose}>取消</button><button className="button primary" disabled={!plan.fields.length||tooMany} onClick={apply}><PackagePlus/>添加 {plan.fields.length} 个字段</button></footer></section></div>
}
