import { useEffect,useState,type Dispatch,type SetStateAction } from 'react'
import { DEFAULT_MOCK_API_OPTIONS, MAX_MOCK_ROUTE_OVERRIDES, type MockApiEnvelope, type MockApiOptions, type MockApiRouteOverride } from '../lib/mockApiOptions'

function NumericSetting({label,ariaLabel,value,min,max,onCommit}:{label:string;ariaLabel:string;value:number;min:number;max:number;onCommit:(value:number)=>void}){
  const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value])
  const commit=()=>{const parsed=Number(draft),next=Number.isFinite(parsed)?Math.max(min,Math.min(max,Math.round(parsed))):value;setDraft(String(next));onCommit(next)}
  return <label>{label}<input aria-label={ariaLabel} inputMode="numeric" value={draft} onChange={event=>setDraft(event.target.value)} onBlur={commit} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur()}}/></label>
}

interface RouteSuggestion { method:MockApiRouteOverride['method'];path:string;label:string }
const routeKey=(route:Pick<MockApiRouteOverride,'method'|'path'>)=>`${route.method} ${route.path}`

export default function MockApiOptionsForm({value,onChange,routeSuggestions}:{value:MockApiOptions;onChange:Dispatch<SetStateAction<MockApiOptions>>;routeSuggestions:RouteSuggestion[]}){
  const updateRule=(index:number,patch:Partial<MockApiRouteOverride>)=>onChange(current=>({...current,routeOverrides:current.routeOverrides.map((rule,ruleIndex)=>ruleIndex===index?{...rule,...patch}:rule)}))
  const addRule=()=>{const used=new Set(value.routeOverrides.map(routeKey)),route=routeSuggestions.find(item=>!used.has(routeKey(item)));if(!route)return;onChange(current=>({...current,routeOverrides:[...current.routeOverrides,{method:route.method,path:route.path,latencyMinMs:current.latencyMinMs,latencyMaxMs:current.latencyMaxMs,failureRate:100,failureStatus:current.failureStatus,failureMessage:'Injected route failure'}]}))}
  return <section className="mock-api-options">
    <header><div><strong>接口场景</strong><span>网络行为与表关系都会写入配置、路由清单和 OpenAPI</span></div><button className="button ghost" onClick={()=>onChange(DEFAULT_MOCK_API_OPTIONS)}>恢复默认</button></header>
    <div className="mock-api-global"><NumericSetting label="延迟最小值（ms）" ariaLabel="Mock API 最小延迟" value={value.latencyMinMs} min={0} max={10_000} onCommit={latencyMinMs=>onChange(current=>({...current,latencyMinMs,latencyMaxMs:Math.max(current.latencyMaxMs,latencyMinMs)}))}/><NumericSetting label="延迟最大值（ms）" ariaLabel="Mock API 最大延迟" value={value.latencyMaxMs} min={value.latencyMinMs} max={10_000} onCommit={latencyMaxMs=>onChange(current=>({...current,latencyMaxMs}))}/><NumericSetting label="确定性失败率（%）" ariaLabel="Mock API 失败率" value={value.failureRate} min={0} max={100} onCommit={failureRate=>onChange(current=>({...current,failureRate}))}/><NumericSetting label="失败状态码" ariaLabel="Mock API 失败状态码" value={value.failureStatus} min={400} max={599} onCommit={failureStatus=>onChange(current=>({...current,failureStatus}))}/><label>成功响应格式<select aria-label="Mock API 响应格式" value={value.envelope} onChange={event=>onChange(current=>({...current,envelope:event.target.value as MockApiEnvelope}))}><option value="plain">原始 JSON</option><option value="data">{'{ data }'}</option><option value="data-meta">{'{ data, meta }'}</option></select></label><label className="mock-api-check"><input aria-label="Mock API 严格校验 Schema" type="checkbox" checked={value.validateSchema} onChange={event=>onChange(current=>({...current,validateSchema:event.target.checked}))}/><span>严格校验类型与约束</span></label><label className="mock-api-check"><input aria-label="Mock API 校验外键" type="checkbox" checked={value.validateForeignKeys} onChange={event=>onChange(current=>({...current,validateForeignKeys:event.target.checked}))}/><span>写入时校验外键</span></label><label>父记录删除<select aria-label="Mock API 删除策略" value={value.deletePolicy} onChange={event=>onChange(current=>({...current,deletePolicy:event.target.value as 'restrict'|'cascade'}))}><option value="restrict">存在子记录时阻止</option><option value="cascade">级联删除所有后代</option></select></label><label className="mock-api-check"><input aria-label="Mock API 嵌套路由" type="checkbox" checked={value.nestedRoutes} onChange={event=>onChange(current=>({...current,nestedRoutes:event.target.checked}))}/><span>生成父子嵌套路由</span></label></div>
    <div className="route-overrides"><header><div><strong>单路由覆盖</strong><span>只改变所选接口；未配置的接口继续使用全局场景</span></div><button className="button ghost" disabled={value.routeOverrides.length>=MAX_MOCK_ROUTE_OVERRIDES||value.routeOverrides.length>=routeSuggestions.length} onClick={addRule}>添加规则</button></header>{value.routeOverrides.length===0?<p>暂无规则。适合定向模拟支付超时、登录限流或单接口故障。</p>:value.routeOverrides.map((rule,index)=><div className="route-rule" key={`${routeKey(rule)}-${index}`}><label>接口<select aria-label={`路由规则 ${index+1} 接口`} value={routeKey(rule)} onChange={event=>{const selected=routeSuggestions.find(item=>routeKey(item)===event.target.value);if(selected)updateRule(index,{method:selected.method,path:selected.path})}}>{routeSuggestions.map(route=><option key={routeKey(route)} value={routeKey(route)}>{route.method} · {route.label} · {route.path}</option>)}</select></label><NumericSetting label="最小延迟" ariaLabel={`路由规则 ${index+1} 最小延迟`} value={rule.latencyMinMs} min={0} max={10_000} onCommit={latencyMinMs=>updateRule(index,{latencyMinMs,latencyMaxMs:Math.max(rule.latencyMaxMs,latencyMinMs)})}/><NumericSetting label="最大延迟" ariaLabel={`路由规则 ${index+1} 最大延迟`} value={rule.latencyMaxMs} min={rule.latencyMinMs} max={10_000} onCommit={latencyMaxMs=>updateRule(index,{latencyMaxMs})}/><NumericSetting label="失败率 %" ariaLabel={`路由规则 ${index+1} 失败率`} value={rule.failureRate} min={0} max={100} onCommit={failureRate=>updateRule(index,{failureRate})}/><NumericSetting label="状态码" ariaLabel={`路由规则 ${index+1} 状态码`} value={rule.failureStatus} min={400} max={599} onCommit={failureStatus=>updateRule(index,{failureStatus})}/><label>错误消息<input aria-label={`路由规则 ${index+1} 错误消息`} maxLength={200} value={rule.failureMessage} onChange={event=>updateRule(index,{failureMessage:event.target.value})}/></label><button className="button danger" aria-label={`删除路由规则 ${index+1}`} onClick={()=>onChange(current=>({...current,routeOverrides:current.routeOverrides.filter((_,ruleIndex)=>ruleIndex!==index)}))}>删除</button></div>)}</div>
  </section>
}
