import { useEffect,useState,type Dispatch,type SetStateAction } from 'react'
import { DEFAULT_MOCK_API_OPTIONS, type MockApiEnvelope, type MockApiOptions } from '../lib/mockApiOptions'

function NumericSetting({label,ariaLabel,value,min,max,onCommit}:{label:string;ariaLabel:string;value:number;min:number;max:number;onCommit:(value:number)=>void}){
  const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value])
  const commit=()=>{const parsed=Number(draft),next=Number.isFinite(parsed)?Math.max(min,Math.min(max,Math.round(parsed))):value;setDraft(String(next));onCommit(next)}
  return <label>{label}<input aria-label={ariaLabel} inputMode="numeric" value={draft} onChange={event=>setDraft(event.target.value)} onBlur={commit} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur()}}/></label>
}

export default function MockApiOptionsForm({value,onChange}:{value:MockApiOptions;onChange:Dispatch<SetStateAction<MockApiOptions>>}){return <section className="mock-api-options"><header><div><strong>接口场景</strong><span>网络行为与表关系都会写入配置、路由清单和 OpenAPI</span></div><button className="button ghost" onClick={()=>onChange(DEFAULT_MOCK_API_OPTIONS)}>恢复默认</button></header><div><NumericSetting label="延迟最小值（ms）" ariaLabel="Mock API 最小延迟" value={value.latencyMinMs} min={0} max={10_000} onCommit={latencyMinMs=>onChange(current=>({...current,latencyMinMs,latencyMaxMs:Math.max(current.latencyMaxMs,latencyMinMs)}))}/><NumericSetting label="延迟最大值（ms）" ariaLabel="Mock API 最大延迟" value={value.latencyMaxMs} min={value.latencyMinMs} max={10_000} onCommit={latencyMaxMs=>onChange(current=>({...current,latencyMaxMs}))}/><NumericSetting label="确定性失败率（%）" ariaLabel="Mock API 失败率" value={value.failureRate} min={0} max={100} onCommit={failureRate=>onChange(current=>({...current,failureRate}))}/><NumericSetting label="失败状态码" ariaLabel="Mock API 失败状态码" value={value.failureStatus} min={400} max={599} onCommit={failureStatus=>onChange(current=>({...current,failureStatus}))}/><label>成功响应格式<select aria-label="Mock API 响应格式" value={value.envelope} onChange={event=>onChange(current=>({...current,envelope:event.target.value as MockApiEnvelope}))}><option value="plain">原始 JSON</option><option value="data">{'{ data }'}</option><option value="data-meta">{'{ data, meta }'}</option></select></label><label className="mock-api-check"><input aria-label="Mock API 校验外键" type="checkbox" checked={value.validateForeignKeys} onChange={event=>onChange(current=>({...current,validateForeignKeys:event.target.checked}))}/><span>写入时校验外键</span></label><label>父记录删除<select aria-label="Mock API 删除策略" value={value.deletePolicy} onChange={event=>onChange(current=>({...current,deletePolicy:event.target.value as 'restrict'|'cascade'}))}><option value="restrict">存在子记录时阻止</option><option value="cascade">级联删除所有后代</option></select></label><label className="mock-api-check"><input aria-label="Mock API 嵌套路由" type="checkbox" checked={value.nestedRoutes} onChange={event=>onChange(current=>({...current,nestedRoutes:event.target.checked}))}/><span>生成父子嵌套路由</span></label></div></section>}
