import { BarChart3, Braces, Check, Database, GitBranch, ListChecks, Search, Table2, Trash2 } from './Icons'
import { useAppStore } from '../store'

const val=(value:unknown)=>value==null?<span className="null">NULL</span>:typeof value==='object'?JSON.stringify(value):String(value)
export default function Preview() {
  const s=useAppStore();const table=s.project.tables.find(t=>t.id===s.activeTableId);const raw=s.result?.data[s.activeTableId]||[];const rows=raw.map((r,index)=>({r,index})).filter(({r})=>(!s.onlyAbnormal||r._mock_meta)&&(!s.query||JSON.stringify(r).toLowerCase().includes(s.query.toLowerCase()))).slice(0,100)
  const fields=table?.fields||[]
  return <section className="preview-pane">
    <nav className="result-tabs"><button className={s.panel==='data'?'active':''} onClick={()=>s.setPanel('data')}><Table2/>数据</button><button className={s.panel==='quality'?'active':''} onClick={()=>s.setPanel('quality')}><ListChecks/>质量检查</button><button className={s.panel==='coverage'?'active':''} onClick={()=>s.setPanel('coverage')}><BarChart3/>覆盖报告</button><button className={s.panel==='relations'?'active':''} onClick={()=>s.setPanel('relations')}><GitBranch/>关系</button><button className={s.panel==='pairwise'?'active':''} onClick={()=>s.setPanel('pairwise')}><GitBranch/>组合</button><button className={s.panel==='states'?'active':''} onClick={()=>s.setPanel('states')}><Database/>状态链</button></nav>
    {s.panel==='data'&&<><div className="preview-tools"><div className="view-switch"><button className={s.preview==='table'?'active':''} onClick={()=>s.setPreview('table')}><Table2/>表格</button><button className={s.preview==='json'?'active':''} onClick={()=>s.setPreview('json')}><Braces/>JSON</button><button className={s.preview==='tree'?'active':''} onClick={()=>s.setPreview('tree')}><GitBranch/>树形</button></div><label className="search-box"><Search/><input value={s.query} onChange={e=>s.setQuery(e.target.value)} placeholder="筛选结果"/></label><label className="checkbox"><input type="checkbox" checked={s.onlyAbnormal} onChange={e=>s.setOnlyAbnormal(e.target.checked)}/>只看异常</label></div>{!s.result?<Empty/>:s.preview==='table'?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>#</th>{fields.map(f=><th key={f.id}>{f.label}<small>{f.name}</small></th>)}<th></th></tr></thead><tbody>{rows.map(({r,index})=><tr key={index} className={r._mock_meta?'abnormal':''}><td>{index+1}</td>{fields.map(f=><td key={f.id} title={String(r[f.name]??'')} contentEditable suppressContentEditableWarning onBlur={e=>s.updateCell(index,f.name,e.currentTarget.textContent)}>{val(r[f.name])}</td>)}<td><button className="icon-button" onClick={()=>s.deleteRow(index)}><Trash2/></button></td></tr>)}</tbody></table>{raw.length>100&&<div className="table-note">为保证流畅，仅预览前 100 条；导出包含全部 {raw.length.toLocaleString()} 条数据。</div>}</div>:<pre className={`json-view ${s.preview}`}>{JSON.stringify(rows.map(x=>x.r),null,2)}</pre>}</>}
    {s.panel==='quality'&&<Quality/>}{s.panel==='coverage'&&<Coverage/>}{s.panel==='relations'&&<Relations/>}{s.panel==='pairwise'&&<Pairwise/>}{s.panel==='states'&&<StateLab/>}
  </section>
}

function Empty(){return <div className="preview-empty"><div className="empty-flask"><span></span><span></span><span></span></div><h3>生产线已就绪</h3><p>当前模板已配置完成，点击顶部“生成数据”即可得到多表关联数据。</p><ul><li><Check/>数据仅在浏览器中生成</li><li><Check/>固定随机种子可重复复现</li><li><Check/>生成后自动执行质量检查</li></ul></div>}
function Quality(){const result=useAppStore(s=>s.result);if(!result)return <Empty/>;return <div className="report-list"><header><div><span>QUALITY GATE</span><h3>数据质量检查</h3></div><strong>{result.report.checks.filter(c=>c.status==='pass').length}/{result.report.checks.length}</strong></header>{result.report.checks.map(c=><article key={c.id} className={c.status}><i>{c.status==='pass'?'✓':c.status==='expected'?'!':'×'}</i><div><strong>{c.label}</strong><span>{c.detail}</span></div><em>{({pass:'通过',warning:'警告',expected:'预期异常',fail:'失败'} as Record<string,string>)[c.status]}</em></article>)}</div>}
function Coverage(){const result=useAppStore(s=>s.result);if(!result)return <Empty/>;return <div className="coverage"><header><span>COVERAGE</span><h3>测试数据覆盖</h3><p>每项覆盖都能追溯到当前 Schema、模式和随机种子。</p></header><div className="coverage-grid">{result.report.coverage.map(c=><article key={c.label}><div className="ring" style={{'--percent':`${c.value*3.6}deg`} as React.CSSProperties}><strong>{c.value}%</strong></div><div><h4>{c.label}</h4><p>{c.detail}</p></div></article>)}</div><div className="manifest"><span>生成清单</span><code>seed={useAppStore.getState().project.seed}</code><code>rows={result.report.totalRows}</code><code>duration={result.report.duration}ms</code><code>{result.report.generatedAt}</code></div></div>}
function Relations(){const project=useAppStore(s=>s.project);const relations=project.tables.flatMap(table=>table.fields.filter(field=>field.ref).map(field=>({from:table,to:project.tables.find(target=>target.id===field.ref!.tableId),field})));return <div className="relations-lab"><header><span>RELATION MAP</span><h3>数据表关系</h3><p>查看当前项目中的主外键依赖和推荐生成顺序。</p></header><div className="relation-order">{project.tables.map((table,index)=><div key={table.id}><i>{index+1}</i><span><strong>{table.label}</strong><code>{table.name}</code></span><em>{table.count} 条</em></div>)}</div><div className="relation-lines">{relations.length?relations.map((relation,index)=><article key={`${relation.from.id}-${relation.field.id}-${index}`}><div><strong>{relation.from.label}</strong><code>{relation.from.name}.{relation.field.name}</code></div><span>引用 →</span><div><strong>{relation.to?.label||'缺失数据表'}</strong><code>{relation.to?.name}.{relation.field.ref?.field}</code></div></article>):<div className="relation-empty">当前项目没有跨表引用。在字段的“引用其他表”中选择主键即可建立关系。</div>}</div></div>}
import { generatePairwise, generateStateEvents, type PairwiseConfig } from '../lib/engine'
import { useState } from 'react'
function Pairwise(){const [dims,setDims]=useState<PairwiseConfig[]>([{name:'设备',values:['iOS','Android','Web']},{name:'登录方式',values:['密码','短信','微信']},{name:'用户状态',values:['正常','冻结','注销']},{name:'网络',values:['WiFi','4G','弱网']}]);const rows=generatePairwise(dims);const full=dims.reduce((n,d)=>n*d.values.length,1);return <div className="lab"><header><span>PAIRWISE LAB</span><h3>两两组合实验室</h3><p>用更少的用例覆盖任意两个参数的所有取值组合。</p></header><div className="lab-metrics"><div><small>全组合</small><strong>{full}</strong></div><div><small>Pairwise</small><strong>{rows.length}</strong></div><div><small>减少</small><strong>{Math.round((1-rows.length/full)*100)}%</strong></div></div><div className="dimension-list">{dims.map((d,i)=><label key={i}><input value={d.name} onChange={e=>setDims(dims.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><textarea value={d.values.join(',')} onChange={e=>setDims(dims.map((x,j)=>j===i?{...x,values:e.target.value.split(',').filter(Boolean)}:x))}/></label>)}</div><div className="pair-table"><table><thead><tr><th>#</th>{dims.map(d=><th>{d.name}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr><td>{i+1}</td>{dims.map(d=><td>{r[d.name]}</td>)}</tr>)}</tbody></table></div></div>}
function StateLab(){const [type,setType]=useState<'order'|'payment'|'logistics'|'quest'>('order');const [error,setError]=useState(false);const project=useAppStore(s=>s.project);const events=generateStateEvents(type,3,project.seed,error);return <div className="lab"><header><span>STATE FLOW</span><h3>业务状态链</h3><p>生成带时间顺序、Trace ID 和合法性标记的连续事件。</p></header><div className="state-controls"><select value={type} onChange={e=>setType(e.target.value as never)}><option value="order">订单状态链</option><option value="payment">支付状态链</option><option value="logistics">物流状态链</option><option value="quest">游戏任务状态链</option></select><label className="checkbox"><input type="checkbox" checked={error} onChange={e=>setError(e.target.checked)}/>注入非法回退</label></div><div className="timeline">{events.map((e,i)=><article className={e.valid?'':'invalid'} key={i}><i></i><div><strong>{e.status}</strong><span>{e.entityId} · {new Date(e.occurredAt).toLocaleString()}</span><code>{e.traceId}</code></div>{!e.valid&&<em>非法迁移</em>}</article>)}</div></div>}
