import { useEffect, useState } from 'react'
import { Check, Database, Layers3, PackagePlus, Plus, Search, Settings2, Trash2, X } from './Icons'
import { TEMPLATES } from '../data/templates'
import { useAppStore } from '../store'
import { plannedProjectCounts } from '../lib/cardinality'

export default function Sidebar({onPool,onFieldPacks}:{onPool:()=>void;onFieldPacks:()=>void}) {
  const s=useAppStore();const table=s.project.tables.find(t=>t.id===s.activeTableId),plannedCounts=plannedProjectCounts(s.project);const fields=table?.fields.filter(f=>`${f.label}${f.name}`.toLowerCase().includes(s.search.toLowerCase()))||[];const[bulk,setBulk]=useState(false),[selected,setSelected]=useState<string[]>([]),[nullable,setNullable]=useState(0),[missing,setMissing]=useState(0),[abnormal,setAbnormal]=useState(0),[distribution,setDistribution]=useState('keep');useEffect(()=>{setSelected([]);setBulk(false)},[s.activeTableId]);const visibleIds=fields.map(field=>field.id),toggle=(fieldId:string)=>setSelected(current=>current.includes(fieldId)?current.filter(id=>id!==fieldId):[...current,fieldId]),allVisible=visibleIds.length>0&&visibleIds.every(id=>selected.includes(id)),toggleAll=()=>setSelected(current=>allVisible?current.filter(id=>!visibleIds.includes(id)):[...new Set([...current,...visibleIds])]),apply=()=>{const patch:Record<string,unknown>={nullable,missing,abnormal};if(distribution!=='keep')patch.distribution=distribution;s.bulkUpdateFields(s.activeTableId,selected,patch);setSelected([]);setBulk(false)},remove=()=>{s.bulkRemoveFields(s.activeTableId,selected);setSelected([]);setBulk(false)}
  return <aside className="sidebar">
    <section className="side-section"><div className="section-title"><span>场景模板</span><small>{TEMPLATES.length} 套</small></div><div className="template-grid">{TEMPLATES.map(t=><button key={t.templateId} className={s.project.templateId===t.templateId?'active':''} onClick={()=>s.chooseTemplate(t.templateId)} title={t.description}><span>{({users:'用户',commerce:'电商',finance:'金融',game:'游戏',community:'社区',logistics:'物流',testing:'通用'} as Record<string,string>)[t.templateId]}</span><small>{t.tables.length} 表</small></button>)}</div></section>
    <section className="side-section table-section"><div className="section-title"><span>数据表</span><div className="section-actions"><small>{s.project.tables.length}</small><button className="icon-button" onClick={s.addTable} title="新增数据表"><Plus size={15}/></button></div></div><div className="table-list">{s.project.tables.map(t=><button key={t.id} className={s.activeTableId===t.id?'active':''} onClick={()=>s.setActiveTable(t.id)}><Database size={14}/><span>{t.label}</span><small title={t.countByReference?'按父记录动态生成':'固定数量'}>{t.countByReference?'≈':''}{plannedCounts[t.id]??t.count}</small></button>)}</div></section>
    <section className={`side-section field-section ${bulk?'bulk-mode':''}`}><div className="section-title"><span>字段</span><div className="section-actions"><button className="icon-button" onClick={onFieldPacks} title="添加字段套餐" aria-label="添加字段套餐"><PackagePlus size={15}/></button><button className={`icon-button ${bulk?'active':''}`} onClick={()=>{setBulk(!bulk);setSelected([])}} title="批量配置字段">{bulk?<X size={15}/>:<Settings2 size={15}/>}</button><button className="icon-button" onClick={s.addField} title="添加字段"><Plus size={15}/></button></div></div><label className="search-box"><Search size={14}/><input placeholder="搜索字段" value={s.search} onChange={e=>s.setSearch(e.target.value)}/></label>{bulk&&<div className="bulk-select-head"><button onClick={toggleAll}><i className={allVisible?'checked':''}>{allVisible?<Check/>:null}</i>{allVisible?'取消当前筛选':'选择当前筛选'}</button><span>{selected.length} 已选</span></div>}<div className="field-list">{fields.map((f,i)=><button key={f.id} className={`${s.selectedFieldId===f.id?'active':''} ${selected.includes(f.id)?'selected':''}`} onClick={()=>bulk?toggle(f.id):s.selectField(f.id)}>{bulk?<i className="field-checkbox">{selected.includes(f.id)?<Check/>:null}</i>:<span className={`type-dot ${f.dataType}`}></span>}<span><strong>{f.label}</strong><small>{f.name}</small></span><em>{i+1}</em></button>)}</div>{bulk&&<div className="bulk-field-panel"><header><strong>批量配置</strong><span>一次操作可撤销</span></header><div><label>空值率<input type="number" min="0" max="100" value={nullable} onChange={event=>setNullable(Math.max(0,Math.min(100,Number(event.target.value))))}/><b>%</b></label><label>缺失率<input type="number" min="0" max="100" value={missing} onChange={event=>setMissing(Math.max(0,Math.min(100,Number(event.target.value))))}/><b>%</b></label><label>异常率<input type="number" min="0" max="100" value={abnormal} onChange={event=>setAbnormal(Math.max(0,Math.min(100,Number(event.target.value))))}/><b>%</b></label><label>真实分布<select value={distribution} onChange={event=>setDistribution(event.target.value)}><option value="keep">保持原配置</option><option value="uniform">均匀</option><option value="normal">正态</option><option value="longTail">长尾</option><option value="hotspot">热点</option><option value="ascending">递增</option><option value="descending">递减</option></select></label></div><footer><button className="icon-button danger" disabled={!selected.length} onClick={remove} title="删除选中字段"><Trash2/></button><button className="button primary" disabled={!selected.length} onClick={apply}>应用到 {selected.length} 个字段</button></footer></div>}</section>
    <section className="pool-entry"><button onClick={onPool}><Layers3 size={16}/><span><strong>自定义数据池</strong><small>{s.pools.length?s.pools.map(p=>p.name).join('、'):'可选 · 内置数据可直接用'}</small></span><Plus size={14}/></button></section>
  </aside>
}
