import { describe,expect,it } from 'vitest'
import { parseCliArgs, runCli } from './cli'

describe('Mock造数 CLI',()=>{
  it('解析模板、种子、时间基准、模式、数量和格式',()=>{expect(parseCliArgs(['--template','users','--seed','42','--reference-date','2030-01-02','--mode','boundary','--count','12','--format','csv','--json'])).toMatchObject({template:'users',seed:42,referenceDate:'2030-01-02T00:00:00.000Z',mode:'boundary',count:12,format:'csv',json:true})})
  it('拒绝未知参数、不安全整数、无效日期和冲突输入',()=>{expect(()=>parseCliArgs(['--wat'])).toThrow(/未知参数/);expect(()=>parseCliArgs(['--count','0'])).toThrow(/1–100000/);expect(()=>parseCliArgs(['--reference-date','not-a-date'])).toThrow(/有效 ISO 日期/);expect(()=>parseCliArgs(['--config','a.mock.json','--template','users'])).toThrow(/不能同时/);expect(()=>parseCliArgs(['--dry-run','--output','x.zip'])).toThrow(/不能与/);expect(()=>parseCliArgs(['--dry-run','--summary','summary.json'])).toThrow(/不能与/)})
  it('默认使用电商完整包且不覆盖文件',()=>{expect(parseCliArgs([])).toMatchObject({template:'commerce',format:'bundle',force:false,dryRun:false,failOnQuality:false})})
  it('支持无需生成数据的 Schema 契约格式',()=>expect(parseCliArgs(['--format','schema','--config','project.mock.json'])).toMatchObject({format:'schema',config:'project.mock.json'}))
  it('支持可直接接入项目的 Mock API 交付格式',()=>expect(parseCliArgs(['--format','mock-api','--template','commerce'])).toMatchObject({format:'mock-api',template:'commerce'}))
  it('解析 Mock API 网络和关系场景并拒绝格式误用',()=>{expect(parseCliArgs(['--format','mock-api','--mock-api-latency','120:480','--mock-api-failure-rate','15','--mock-api-failure-status','429','--mock-api-envelope','data-meta','--mock-api-strict-schema','--mock-api-delete','cascade','--mock-api-no-fk-check','--mock-api-no-nested']).mockApi).toEqual({latencyMinMs:120,latencyMaxMs:480,failureRate:15,failureStatus:429,envelope:'data-meta',validateSchema:true,validateForeignKeys:false,deletePolicy:'cascade',nestedRoutes:false,routeOverrides:[]});expect(()=>parseCliArgs(['--format','csv','--mock-api-failure-rate','10'])).toThrow(/只能与/);expect(()=>parseCliArgs(['--format','mock-api','--mock-api-latency','500:100'])).toThrow(/不能小于/);expect(()=>parseCliArgs(['--format','mock-api','--mock-api-envelope','wat'])).toThrow(/仅支持/);expect(()=>parseCliArgs(['--format','mock-api','--mock-api-delete','wat'])).toThrow(/仅支持/)})
  it('支持重复声明并安全规范化单路由场景',()=>{const parsed=parseCliArgs(['--format','mock-api','--mock-api-route','post|/api/payments|120:500|30|429|支付渠道限流','--mock-api-route','GET|/api/orders/:id|0|100|503|订单服务不可用','--mock-api-route','PUT|/api/orders/:id|0|100|409|订单替换冲突']);expect(parsed.mockApi?.routeOverrides).toEqual([{method:'POST',path:'/api/payments',latencyMinMs:120,latencyMaxMs:500,failureRate:30,failureStatus:429,failureMessage:'支付渠道限流'},{method:'GET',path:'/api/orders/:id',latencyMinMs:0,latencyMaxMs:0,failureRate:100,failureStatus:503,failureMessage:'订单服务不可用'},{method:'PUT',path:'/api/orders/:id',latencyMinMs:0,latencyMaxMs:0,failureRate:100,failureStatus:409,failureMessage:'订单替换冲突'}]);expect(()=>parseCliArgs(['--format','mock-api','--mock-api-route','GET|https://evil.test|0|100|503|x'])).toThrow(/只能与|格式/);expect(()=>parseCliArgs(['--format','mock-api','--mock-api-route','GET|\/api\/users|500:100|10|503|x'])).toThrow(/不能小于/)})
  it('生成前拒绝当前 Schema 中不存在的路由场景',async()=>{await expect(runCli(parseCliArgs(['--format','mock-api','--template','users','--mock-api-route','POST|/api/payments|0|100|429|x','--output','/tmp/never-created.zip']))).rejects.toThrow(/不匹配.*payments/)})
  it('dry-run 使用动态基数计划量，count 覆盖会切回固定数量',async()=>{
    const dynamic=await runCli({...parseCliArgs(['--template','commerce','--dry-run']),dryRun:true}),fixed=await runCli({...parseCliArgs(['--template','commerce','--count','2','--dry-run']),dryRun:true})
    expect(dynamic).toMatchObject({dryRun:true,plannedRows:239});expect(fixed).toMatchObject({dryRun:true,plannedRows:10})
  })
})
