import { create } from 'zustand'
import { createJSONStorage, persist, type StateStorage } from 'zustand/middleware'
import { cloneTemplate } from './data/templates'
import { refreshGeneratedResult } from './lib/modeling'
import type { DataPool, DataRow, GenerateResult, ProjectSchema } from './types'
import { diagnoseProject, type DiagnosticIssue } from './lib/diagnostics'
import { generationHistoryStore } from './lib/generationHistory'
import { clearShareHash, sharedProjectFromHash } from './lib/share'

interface AppState {
  project:ProjectSchema; activeTableId:string; selectedFieldId:string; result:GenerateResult|null; pools:DataPool[]; search:string; preview:'table'|'json'|'tree'; panel:'data'|'quality'|'coverage'|'pairwise'|'states'|'relations'|'diagnostics'|'statistics'; query:string; onlyAbnormal:boolean; qualityFocus:{tableId:string;rowIndexes:number[]}|null; isGenerating:boolean; generationError:string; past:ProjectSchema[]; future:ProjectSchema[]; diagnostics:DiagnosticIssue[]; lockedFields:string[];
  setProject:(p:ProjectSchema)=>void; chooseTemplate:(id:string)=>void; setActiveTable:(id:string)=>void; selectField:(id:string)=>void; updateProject:(patch:Partial<ProjectSchema>)=>void; updateTable:(id:string,patch:Record<string,unknown>)=>void; updateField:(tableId:string,fieldId:string,patch:Record<string,unknown>)=>void; bulkUpdateFields:(tableId:string,fieldIds:string[],patch:Record<string,unknown>)=>void; bulkRemoveFields:(tableId:string,fieldIds:string[])=>void; addTable:()=>void; duplicateTable:(id:string)=>void; removeTable:(id:string)=>void; moveTable:(id:string,direction:-1|1)=>void; addField:()=>void; removeField:(id:string)=>void; duplicateField:(id:string)=>void; moveField:(id:string,direction:-1|1)=>void; undo:()=>void; redo:()=>void; generate:()=>Promise<void>; cancelGenerate:()=>void; supplementCoverage:()=>Promise<void>; focusQualityIssue:(tableId:string,fieldId:string|undefined,rowIndexes:number[])=>void; clearQualityFocus:()=>void; setResult:(r:GenerateResult|null)=>void; setPools:(p:DataPool[])=>void; setSearch:(s:string)=>void; setPreview:(p:'table'|'json'|'tree')=>void; setPanel:(p:AppState['panel'])=>void; setQuery:(s:string)=>void; setOnlyAbnormal:(v:boolean)=>void; toggleFieldLock:(name:string)=>void; deleteRow:(index:number)=>void; regenerateRow:(index:number)=>Promise<void>; updateCell:(index:number,key:string,value:unknown)=>void;
}
const sharedStartup=(()=>{if(typeof location==='undefined'||!location.hash.includes('share='))return{project:null,error:''};try{const shared=sharedProjectFromHash(location.hash);return{project:shared?{...shared,id:`shared_${Date.now()}`,name:`${shared.name} · 分享副本`}:null,error:''}}catch(error){return{project:null,error:error instanceof Error?`分享链接无法打开：${error.message}`:'分享链接无法打开'}}finally{clearShareHash()}})()
const initial=sharedStartup.project??cloneTemplate('commerce')
let activeWorker:Worker|null=null
const remember=(state:AppState,project:ProjectSchema)=>({project,past:[...state.past.slice(-29),structuredClone(state.project)],future:[],result:null,diagnostics:diagnoseProject(project),generationError:'',qualityFocus:null})
const uniqueTableName=(tables:ProjectSchema['tables'],base='new_table')=>{let name=base,index=2;const names=new Set(tables.map(table=>table.name));while(names.has(name))name=`${base}_${index++}`;return name}
const memoryValues=new Map<string,string>()
const memoryStorage:StateStorage={getItem:key=>memoryValues.get(key)??null,setItem:(key,value)=>{memoryValues.set(key,value)},removeItem:key=>{memoryValues.delete(key)}}
export const useAppStore=create<AppState>()(persist((set,get)=>({
  project:initial,activeTableId:initial.tables[0].id,selectedFieldId:initial.tables[0].fields[0].id,result:null,pools:[],search:'',preview:'table',panel:'data',query:'',onlyAbnormal:false,qualityFocus:null,isGenerating:false,generationError:sharedStartup.error,past:[],future:[],diagnostics:diagnoseProject(initial),lockedFields:[],
  setProject:(project)=>set(s=>({...remember(s,project),activeTableId:project.tables[0]?.id||'',selectedFieldId:project.tables[0]?.fields[0]?.id||'',lockedFields:[]})),
  chooseTemplate:(id)=>get().setProject(cloneTemplate(id)), setActiveTable:(activeTableId)=>set({activeTableId,selectedFieldId:get().project.tables.find(t=>t.id===activeTableId)?.fields[0]?.id||'',lockedFields:[],qualityFocus:null}),selectField:(selectedFieldId)=>set({selectedFieldId}),
  updateProject:(patch)=>set(s=>remember(s,{...s.project,...patch})),
  updateTable:(id,patch)=>set(s=>remember(s,{...s.project,tables:s.project.tables.map(t=>t.id===id?{...t,...patch}:t)})),
  updateField:(tableId,fieldId,patch)=>set(s=>remember(s,{...s.project,tables:s.project.tables.map(t=>t.id===tableId?{...t,fields:t.fields.map(f=>f.id===fieldId?{...f,...patch}:f)}:t)})),
  bulkUpdateFields:(tableId,fieldIds,patch)=>set(s=>{const selected=new Set(fieldIds);if(!selected.size)return{};return remember(s,{...s.project,tables:s.project.tables.map(table=>table.id===tableId?{...table,fields:table.fields.map(field=>selected.has(field.id)?{...field,...patch}:field)}:table)})}),
  bulkRemoveFields:(tableId,fieldIds)=>set(s=>{const selected=new Set(fieldIds),table=s.project.tables.find(candidate=>candidate.id===tableId);if(!table||!selected.size)return{};if(table.fields.length-selected.size<1)return{generationError:'每张数据表至少需要保留一个字段'};const protectedNames=new Set(s.project.tables.flatMap(candidate=>candidate.fields.filter(field=>field.ref?.tableId===tableId).map(field=>field.ref!.field))),protectedFields=table.fields.filter(field=>selected.has(field.id)&&protectedNames.has(field.name));if(protectedFields.length)return{generationError:`字段 ${protectedFields.map(field=>field.name).join('、')} 仍被外键引用，不能批量删除`};const project={...s.project,tables:s.project.tables.map(candidate=>candidate.id===tableId?{...candidate,fields:candidate.fields.filter(field=>!selected.has(field.id))}:candidate)};return{...remember(s,project),selectedFieldId:table.fields.find(field=>!selected.has(field.id))?.id||'',generationError:''}}),
  addTable:()=>set(s=>{const id=`table_${Date.now()}`,fieldId=`field_${Date.now()}`,name=uniqueTableName(s.project.tables);const project={...s.project,tables:[...s.project.tables,{id,name,label:'新数据表',count:20,fields:[{id:fieldId,name:'id',label:'ID',generator:'autoId',dataType:'number' as const,primaryKey:true,unique:true,min:1}]}]};return{...remember(s,project),activeTableId:id,selectedFieldId:fieldId}}),
  duplicateTable:(id)=>set(s=>{const source=s.project.tables.find(table=>table.id===id);if(!source)return{};const now=Date.now(),newId=`table_${now}`,newName=uniqueTableName(s.project.tables,`${source.name}_copy`);const fields=source.fields.map((field,index)=>({...structuredClone(field),id:`field_${now}_${index}`,name:field.name,ref:field.ref?.tableId===source.id?{...field.ref,tableId:newId}:field.ref}));const project={...s.project,tables:[...s.project.tables,{...structuredClone(source),id:newId,name:newName,label:`${source.label}副本`,fields}]};return{...remember(s,project),activeTableId:newId,selectedFieldId:fields[0]?.id||''}}),
  removeTable:(id)=>set(s=>{if(s.project.tables.length<=1)return{};const referenced=s.project.tables.some(table=>table.id!==id&&table.fields.some(field=>field.ref?.tableId===id));if(referenced)return{generationError:'该数据表仍被其他表引用，请先移除引用'};const tables=s.project.tables.filter(table=>table.id!==id),project={...s.project,tables};const next=tables[0];return{...remember(s,project),activeTableId:next.id,selectedFieldId:next.fields[0]?.id||'',generationError:''}}),
  moveTable:(id,direction)=>set(s=>{const tables=[...s.project.tables],index=tables.findIndex(table=>table.id===id),target=index+direction;if(index<0||target<0||target>=tables.length)return{};[tables[index],tables[target]]=[tables[target],tables[index]];return remember(s,{...s.project,tables})}),
  addField:()=>set(s=>{const id=`f_${Date.now()}`;const project={...s.project,tables:s.project.tables.map(t=>t.id===s.activeTableId?{...t,fields:[...t.fields,{id,name:`field_${t.fields.length+1}`,label:'新字段',generator:'randomString',dataType:'string' as const}]}:t)};return{...remember(s,project),selectedFieldId:id}}),
  removeField:(id)=>set(s=>{const project={...s.project,tables:s.project.tables.map(t=>t.id===s.activeTableId&&t.fields.length>1?{...t,fields:t.fields.filter(f=>f.id!==id)}:t)};return{...remember(s,project),selectedFieldId:''}}),
  duplicateField:(id)=>set(s=>{const project={...s.project,tables:s.project.tables.map(t=>{if(t.id!==s.activeTableId)return t;const source=t.fields.find(f=>f.id===id);return source?{...t,fields:[...t.fields,{...source,id:`f_${Date.now()}`,name:`${source.name}_copy`,label:`${source.label}副本`}]}:t})};return remember(s,project)}),
  moveField:(id,direction)=>set(s=>{const project={...s.project,tables:s.project.tables.map(t=>{if(t.id!==s.activeTableId)return t;const fields=[...t.fields],i=fields.findIndex(f=>f.id===id),j=i+direction;if(i<0||j<0||j>=fields.length)return t;[fields[i],fields[j]]=[fields[j],fields[i]];return{...t,fields}})};return remember(s,project)}),
  undo:()=>{const s=get(),project=s.past[s.past.length-1];if(!project)return;const active=project.tables.some(table=>table.id===s.activeTableId)?s.activeTableId:project.tables[0].id;set({project:structuredClone(project),past:s.past.slice(0,-1),future:[structuredClone(s.project),...s.future.slice(0,29)],activeTableId:active,selectedFieldId:project.tables.find(table=>table.id===active)?.fields[0]?.id||'',result:null,diagnostics:diagnoseProject(project),generationError:''})},
  redo:()=>{const s=get(),project=s.future[0];if(!project)return;const active=project.tables.some(table=>table.id===s.activeTableId)?s.activeTableId:project.tables[0].id;set({project:structuredClone(project),past:[...s.past.slice(-29),structuredClone(s.project)],future:s.future.slice(1),activeTableId:active,selectedFieldId:project.tables.find(table=>table.id===active)?.fields[0]?.id||'',result:null,diagnostics:diagnoseProject(project),generationError:''})},
  generate:async()=>{const s=get(),runProject=structuredClone(s.project);const diagnostics=diagnoseProject(runProject),errors=diagnostics.filter(issue=>issue.level==='error');if(errors.length){set({diagnostics,panel:'diagnostics',generationError:`生成前检查发现 ${errors.length} 个阻断问题，请先修复。`,isGenerating:false});return}const poolMap=Object.fromEntries(s.pools.map(p=>[p.name,p.values]));set({isGenerating:true,generationError:'',panel:'data',diagnostics,qualityFocus:null});if(typeof Worker==='undefined'){try{const{generateProject}=await import('./lib/engine'),result=generateProject(runProject,poolMap);set({result,isGenerating:false});void generationHistoryStore.record(runProject,result).catch(()=>{})}catch(error){set({generationError:error instanceof Error?error.message:'生成失败',isGenerating:false})}return}activeWorker?.terminate();activeWorker=new Worker(new URL('./workers/generator.worker.ts',import.meta.url),{type:'module'});activeWorker.onmessage=(event:MessageEvent<{ok:boolean;result?:GenerateResult;error?:string}>)=>{if(event.data.ok){const result=event.data.result!;set({result,isGenerating:false});void generationHistoryStore.record(runProject,result).catch(()=>{})}else set({generationError:event.data.error||'生成失败',isGenerating:false});activeWorker?.terminate();activeWorker=null};activeWorker.onerror=()=>{set({generationError:'生成任务执行失败',isGenerating:false});activeWorker?.terminate();activeWorker=null};activeWorker.postMessage({project:runProject,pools:poolMap})},
  cancelGenerate:()=>{activeWorker?.terminate();activeWorker=null;set({isGenerating:false,generationError:'已取消本次生成'})},setResult:(result)=>set({result}),setPools:(pools)=>set({pools}),setSearch:(search)=>set({search}),setPreview:(preview)=>set({preview}),setPanel:(panel)=>set({panel}),setQuery:(query)=>set({query}),setOnlyAbnormal:(onlyAbnormal)=>set({onlyAbnormal}),toggleFieldLock:(name)=>set(s=>({lockedFields:s.lockedFields.includes(name)?s.lockedFields.filter(field=>field!==name):[...s.lockedFields,name]})),
  focusQualityIssue:(activeTableId,selectedFieldId,rowIndexes)=>set({activeTableId,selectedFieldId:selectedFieldId||get().project.tables.find(table=>table.id===activeTableId)?.fields[0]?.id||'',panel:'data',preview:'table',query:'',onlyAbnormal:false,qualityFocus:rowIndexes.length?{tableId:activeTableId,rowIndexes}:null,lockedFields:[]}),clearQualityFocus:()=>set({qualityFocus:null}),
  supplementCoverage:async()=>{const s=get();if(!s.result||!s.result.report.gaps.length)return;const{supplementCoverageGaps}=await import('./lib/engine'),supplemented=supplementCoverageGaps(s.project,s.result.data,Object.fromEntries(s.pools.map(pool=>[pool.name,pool.values])),s.result.report.gaps),result=refreshGeneratedResult(supplemented.project,s.result,supplemented.data);set({project:supplemented.project,result,past:[...s.past.slice(-29),structuredClone(s.project)],future:[],diagnostics:diagnoseProject(supplemented.project),generationError:supplemented.added?`已追加 ${supplemented.added} 条最小覆盖数据。`:''})},
  deleteRow:(index)=>set(s=>{if(!s.result)return{};const rows=[...(s.result.data[s.activeTableId]||[])];rows.splice(index,1);const data={...s.result.data,[s.activeTableId]:rows};return{result:refreshGeneratedResult(s.project,s.result,data)}}),
  regenerateRow:async(index)=>{const s=get();if(!s.result)return;const{regenerateDataRow}=await import('./lib/engine'),row=regenerateDataRow(s.project,s.result.data,s.activeTableId,index,Object.fromEntries(s.pools.map(pool=>[pool.name,pool.values])),s.lockedFields),rows=(s.result.data[s.activeTableId]||[]).map((value,rowIndex)=>rowIndex===index?row:value),data={...s.result.data,[s.activeTableId]:rows};set({result:refreshGeneratedResult(s.project,s.result,data)})},
  updateCell:(index,key,value)=>set(s=>{if(!s.result)return{};const field=s.project.tables.find(table=>table.id===s.activeTableId)?.fields.find(candidate=>candidate.name===key);let parsed=value;if(typeof value==='string'){if(value.trim().toUpperCase()==='NULL')parsed=null;else if(field?.dataType==='number'){const number=Number(value);parsed=Number.isFinite(number)?number:value}else if(field?.dataType==='boolean')parsed=value==='true'?true:value==='false'?false:value}const rows=(s.result.data[s.activeTableId]||[]).map((r,i)=>i===index?{...r,[key]:parsed}:r),data={...s.result.data,[s.activeTableId]:rows};return{result:refreshGeneratedResult(s.project,s.result,data)}}),
}),{name:'mock-tool-ui',storage:createJSONStorage(()=>typeof localStorage==='undefined'?memoryStorage:localStorage),partialize:s=>({project:s.project,activeTableId:s.activeTableId,selectedFieldId:s.selectedFieldId,pools:s.pools}),merge:(persisted,current)=>{const saved=persisted as Partial<AppState>;if(sharedStartup.project)return{...current,pools:saved.pools??current.pools,diagnostics:diagnoseProject(current.project)};const merged={...current,...saved};return{...merged,diagnostics:diagnoseProject(merged.project)}}}))
