import { create } from 'zustand'
import { createJSONStorage, persist, type StateStorage } from 'zustand/middleware'
import { cloneTemplate } from './data/templates'
import { generateProject } from './lib/engine'
import type { DataPool, DataRow, GenerateResult, ProjectSchema } from './types'

interface AppState {
  project:ProjectSchema; activeTableId:string; selectedFieldId:string; result:GenerateResult|null; pools:DataPool[]; search:string; preview:'table'|'json'|'tree'; panel:'data'|'quality'|'coverage'|'pairwise'|'states'|'relations'; query:string; onlyAbnormal:boolean; isGenerating:boolean; generationError:string; past:ProjectSchema[]; future:ProjectSchema[];
  setProject:(p:ProjectSchema)=>void; chooseTemplate:(id:string)=>void; setActiveTable:(id:string)=>void; selectField:(id:string)=>void; updateProject:(patch:Partial<ProjectSchema>)=>void; updateTable:(id:string,patch:Record<string,unknown>)=>void; updateField:(tableId:string,fieldId:string,patch:Record<string,unknown>)=>void; addTable:()=>void; duplicateTable:(id:string)=>void; removeTable:(id:string)=>void; moveTable:(id:string,direction:-1|1)=>void; addField:()=>void; removeField:(id:string)=>void; duplicateField:(id:string)=>void; moveField:(id:string,direction:-1|1)=>void; undo:()=>void; redo:()=>void; generate:()=>void; cancelGenerate:()=>void; setResult:(r:GenerateResult|null)=>void; setPools:(p:DataPool[])=>void; setSearch:(s:string)=>void; setPreview:(p:'table'|'json'|'tree')=>void; setPanel:(p:AppState['panel'])=>void; setQuery:(s:string)=>void; setOnlyAbnormal:(v:boolean)=>void; deleteRow:(index:number)=>void; updateCell:(index:number,key:string,value:unknown)=>void;
}
const initial=cloneTemplate('commerce')
let activeWorker:Worker|null=null
const remember=(state:AppState,project:ProjectSchema)=>({project,past:[...state.past.slice(-29),structuredClone(state.project)],future:[],result:null})
const uniqueTableName=(tables:ProjectSchema['tables'],base='new_table')=>{let name=base,index=2;const names=new Set(tables.map(table=>table.name));while(names.has(name))name=`${base}_${index++}`;return name}
const memoryValues=new Map<string,string>()
const memoryStorage:StateStorage={getItem:key=>memoryValues.get(key)??null,setItem:(key,value)=>{memoryValues.set(key,value)},removeItem:key=>{memoryValues.delete(key)}}
export const useAppStore=create<AppState>()(persist((set,get)=>({
  project:initial,activeTableId:initial.tables[0].id,selectedFieldId:initial.tables[0].fields[0].id,result:null,pools:[],search:'',preview:'table',panel:'data',query:'',onlyAbnormal:false,isGenerating:false,generationError:'',past:[],future:[],
  setProject:(project)=>set(s=>({...remember(s,project),activeTableId:project.tables[0]?.id||'',selectedFieldId:project.tables[0]?.fields[0]?.id||''})),
  chooseTemplate:(id)=>get().setProject(cloneTemplate(id)), setActiveTable:(activeTableId)=>set({activeTableId,selectedFieldId:get().project.tables.find(t=>t.id===activeTableId)?.fields[0]?.id||''}),selectField:(selectedFieldId)=>set({selectedFieldId}),
  updateProject:(patch)=>set(s=>remember(s,{...s.project,...patch})),
  updateTable:(id,patch)=>set(s=>remember(s,{...s.project,tables:s.project.tables.map(t=>t.id===id?{...t,...patch}:t)})),
  updateField:(tableId,fieldId,patch)=>set(s=>remember(s,{...s.project,tables:s.project.tables.map(t=>t.id===tableId?{...t,fields:t.fields.map(f=>f.id===fieldId?{...f,...patch}:f)}:t)})),
  addTable:()=>set(s=>{const id=`table_${Date.now()}`,fieldId=`field_${Date.now()}`,name=uniqueTableName(s.project.tables);const project={...s.project,tables:[...s.project.tables,{id,name,label:'新数据表',count:20,fields:[{id:fieldId,name:'id',label:'ID',generator:'autoId',dataType:'number' as const,primaryKey:true,unique:true,min:1}]}]};return{...remember(s,project),activeTableId:id,selectedFieldId:fieldId}}),
  duplicateTable:(id)=>set(s=>{const source=s.project.tables.find(table=>table.id===id);if(!source)return{};const now=Date.now(),newId=`table_${now}`,newName=uniqueTableName(s.project.tables,`${source.name}_copy`);const fields=source.fields.map((field,index)=>({...structuredClone(field),id:`field_${now}_${index}`,name:field.name,ref:field.ref?.tableId===source.id?{...field.ref,tableId:newId}:field.ref}));const project={...s.project,tables:[...s.project.tables,{...structuredClone(source),id:newId,name:newName,label:`${source.label}副本`,fields}]};return{...remember(s,project),activeTableId:newId,selectedFieldId:fields[0]?.id||''}}),
  removeTable:(id)=>set(s=>{if(s.project.tables.length<=1)return{};const referenced=s.project.tables.some(table=>table.id!==id&&table.fields.some(field=>field.ref?.tableId===id));if(referenced)return{generationError:'该数据表仍被其他表引用，请先移除引用'};const tables=s.project.tables.filter(table=>table.id!==id),project={...s.project,tables};const next=tables[0];return{...remember(s,project),activeTableId:next.id,selectedFieldId:next.fields[0]?.id||'',generationError:''}}),
  moveTable:(id,direction)=>set(s=>{const tables=[...s.project.tables],index=tables.findIndex(table=>table.id===id),target=index+direction;if(index<0||target<0||target>=tables.length)return{};[tables[index],tables[target]]=[tables[target],tables[index]];return remember(s,{...s.project,tables})}),
  addField:()=>set(s=>{const id=`f_${Date.now()}`;const project={...s.project,tables:s.project.tables.map(t=>t.id===s.activeTableId?{...t,fields:[...t.fields,{id,name:`field_${t.fields.length+1}`,label:'新字段',generator:'randomString',dataType:'string' as const}]}:t)};return{...remember(s,project),selectedFieldId:id}}),
  removeField:(id)=>set(s=>{const project={...s.project,tables:s.project.tables.map(t=>t.id===s.activeTableId&&t.fields.length>1?{...t,fields:t.fields.filter(f=>f.id!==id)}:t)};return{...remember(s,project),selectedFieldId:''}}),
  duplicateField:(id)=>set(s=>{const project={...s.project,tables:s.project.tables.map(t=>{if(t.id!==s.activeTableId)return t;const source=t.fields.find(f=>f.id===id);return source?{...t,fields:[...t.fields,{...source,id:`f_${Date.now()}`,name:`${source.name}_copy`,label:`${source.label}副本`}]}:t})};return remember(s,project)}),
  moveField:(id,direction)=>set(s=>{const project={...s.project,tables:s.project.tables.map(t=>{if(t.id!==s.activeTableId)return t;const fields=[...t.fields],i=fields.findIndex(f=>f.id===id),j=i+direction;if(i<0||j<0||j>=fields.length)return t;[fields[i],fields[j]]=[fields[j],fields[i]];return{...t,fields}})};return remember(s,project)}),
  undo:()=>{const s=get(),project=s.past[s.past.length-1];if(!project)return;const active=project.tables.some(table=>table.id===s.activeTableId)?s.activeTableId:project.tables[0].id;set({project:structuredClone(project),past:s.past.slice(0,-1),future:[structuredClone(s.project),...s.future.slice(0,29)],activeTableId:active,selectedFieldId:project.tables.find(table=>table.id===active)?.fields[0]?.id||'',result:null})},
  redo:()=>{const s=get(),project=s.future[0];if(!project)return;const active=project.tables.some(table=>table.id===s.activeTableId)?s.activeTableId:project.tables[0].id;set({project:structuredClone(project),past:[...s.past.slice(-29),structuredClone(s.project)],future:s.future.slice(1),activeTableId:active,selectedFieldId:project.tables.find(table=>table.id===active)?.fields[0]?.id||'',result:null})},
  generate:()=>{const s=get();const poolMap=Object.fromEntries(s.pools.map(p=>[p.name,p.values]));const total=s.project.tables.reduce((n,t)=>n+t.count,0);set({isGenerating:true,generationError:'',panel:'data'});if(total<=1000||typeof Worker==='undefined'){try{set({result:generateProject(s.project,poolMap),isGenerating:false})}catch(error){set({generationError:error instanceof Error?error.message:'生成失败',isGenerating:false})}return}activeWorker?.terminate();activeWorker=new Worker(new URL('./workers/generator.worker.ts',import.meta.url),{type:'module'});activeWorker.onmessage=(event:MessageEvent<{ok:boolean;result?:GenerateResult;error?:string}>)=>{event.data.ok?set({result:event.data.result!,isGenerating:false}):set({generationError:event.data.error||'生成失败',isGenerating:false});activeWorker?.terminate();activeWorker=null};activeWorker.onerror=()=>{set({generationError:'生成任务执行失败',isGenerating:false});activeWorker?.terminate();activeWorker=null};activeWorker.postMessage({project:s.project,pools:poolMap})},
  cancelGenerate:()=>{activeWorker?.terminate();activeWorker=null;set({isGenerating:false,generationError:'已取消本次生成'})},setResult:(result)=>set({result}),setPools:(pools)=>set({pools}),setSearch:(search)=>set({search}),setPreview:(preview)=>set({preview}),setPanel:(panel)=>set({panel}),setQuery:(query)=>set({query}),setOnlyAbnormal:(onlyAbnormal)=>set({onlyAbnormal}),
  deleteRow:(index)=>set(s=>{if(!s.result)return{};const rows=[...(s.result.data[s.activeTableId]||[])];rows.splice(index,1);return{result:{...s.result,data:{...s.result.data,[s.activeTableId]:rows}}}}),
  updateCell:(index,key,value)=>set(s=>{if(!s.result)return{};const rows=(s.result.data[s.activeTableId]||[]).map((r,i)=>i===index?{...r,[key]:value}:r);return{result:{...s.result,data:{...s.result.data,[s.activeTableId]:rows}}}}),
}),{name:'mock-tool-ui',storage:createJSONStorage(()=>typeof localStorage==='undefined'?memoryStorage:localStorage),partialize:s=>({project:s.project,activeTableId:s.activeTableId,selectedFieldId:s.selectedFieldId,pools:s.pools})}))
